(() => {
  const KEY='kairos-mvp-state', GRACE=24*60*60*1000, CHECK=30000;
  const core=window.KairosReminderCore||{
    reminderMinutes:item=>item.reminder==='none'||item.reminder==null||item.reminder===''?null:Number.isFinite(Number(item.reminder))?Number(item.reminder):null,
    dueAt:item=>{const minutes=item.reminder==='none'||item.reminder==null||item.reminder===''?null:Number(item.reminder);if(minutes==null||Number.isNaN(minutes)||!item.date)return null;const time=item.all_day?'09:00':item.start_time||'09:00';const date=new Date(`${item.date}T${time}:00`);return Number.isNaN(+date)?null:new Date(+date-minutes*60000)},
    targetTime:(item,m)=>m.snoozedUntil||+(core.dueAt(item)||0),
    classifyReminder:(item,m,now)=>{if(item.status==='done'||m.dismissedAt||m.firedAt&&!m.snoozedUntil)return null;const target=m.snoozedUntil||+(core.dueAt(item)||0);return target&&target<=now&&target>=now-GRACE?{target,missed:now-target>CHECK*1.5}:null}
  };
  let state, timer, lastCheck=Date.now(), toastTimer;
  const load=()=>state || { schedules:[], reminders:{} };
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const readSettings=()=>{try{return window.KairosSettingsFeature?.read?.()||{}}catch{return {}}};
  const snoozeMinutes=()=>{const value=Number(readSettings()?.reminders?.snoozeMinutes||10);return Number.isFinite(value)&&value>0?value:10};
  const desktopNotificationsEnabled=()=>readSettings()?.reminders?.desktopNotifications!==false;
  const snoozeLabel=()=>`Snooze ${snoozeMinutes()} min`;
  function dueAt(item){return core.dueAt(item)}
  const meta=id=>state.reminders[id]||{};
  function save(){window.kairosDesktop?.appState.save(state).catch(console.error)}
  function upcoming(){const now=Date.now();return state.schedules.filter(x=>x.status!=='done'&&!meta(x.id).dismissedAt&&dueAt(x)&&+dueAt(x)>=now).sort((a,b)=>dueAt(a)-dueAt(b))}
  function pending(){return state.schedules.filter(x=>meta(x.id).firedAt&&!meta(x.id).dismissedAt&&x.status!=='done').sort((a,b)=>meta(b.id).firedAt-meta(a.id).firedAt)}
  function timeText(item){const d=dueAt(item);return d?(window.KairosI18n?.formatDate?.(d,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})||d.toLocaleString()):''}
  function ensureUI(){if(document.getElementById('kairosReminderPanel'))return;document.body.insertAdjacentHTML('beforeend',`<section id="kairosReminderPanel" class="kairos-reminder-panel" hidden><div class="kairos-reminder-head"><h2>Reminders</h2><button data-close aria-label="Close">×</button></div><div class="kairos-reminder-list"></div></section>`);document.querySelector('.kairos-reminder-button')?.addEventListener('click',toggle);document.querySelector('[data-close]',document.getElementById('kairosReminderPanel')).onclick=event=>{event.stopPropagation();toggle(false)};document.addEventListener('click',e=>{if(!e.target.closest('.kairos-reminder-panel,.kairos-reminder-button'))toggle(false)})}
  function render(){ensureUI();const active=pending(),next=upcoming().slice(0,8),items=[...active,...next.filter(x=>!active.includes(x))],label=escape(snoozeLabel());const list=document.querySelector('.kairos-reminder-list');list.innerHTML=items.length?items.map(x=>`<article class="kairos-reminder-item"><button class="kairos-reminder-dismiss" data-dismiss="${x.id}" aria-label="Dismiss reminder" title="Dismiss">×</button><strong>${escape(x.title)}</strong><p>${meta(x.id).firedAt?'Due now':'Scheduled'} · ${escape(timeText(x))}</p><div class="kairos-reminder-actions"><button data-done="${x.id}">Complete</button><button data-snooze="${x.id}">${label}</button><button data-open="${x.id}">Details</button></div></article>`).join(''):'<div class="kairos-reminder-empty">No reminders<br><small>Upcoming reminders will appear here.</small></div>';list.querySelectorAll('[data-dismiss]').forEach(b=>b.onclick=e=>{e.stopPropagation();dismiss(b.dataset.dismiss)});list.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>complete(b.dataset.done));list.querySelectorAll('[data-snooze]').forEach(b=>b.onclick=()=>snooze(b.dataset.snooze));list.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open));const badge=document.querySelector('.kairos-reminder-badge');if(badge){badge.hidden=!active.length;badge.textContent=active.length>9?'9+':String(active.length)}}
  function toggle(force){ensureUI();const panel=document.getElementById('kairosReminderPanel'),show=force??panel.hidden;panel.hidden=!show;document.querySelector('.kairos-reminder-button')?.setAttribute('aria-expanded',String(show));if(show)render()}
  function complete(id){state=load();const item=state.schedules.find(x=>x.id===id);if(!item)return;item.status='done';item.updated_at=new Date().toISOString();state.reminders=state.reminders||{};state.reminders[id]={...(state.reminders[id]||{}),dismissedAt:Date.now(),snoozedUntil:null};save();document.querySelector('.kairos-reminder-toast')?.remove();render();window.dispatchEvent(new CustomEvent('kairos:state-changed',{detail:state}));window.renderSchedules?.()}
  function snooze(id){state.reminders[id]={...meta(id),snoozedUntil:Date.now()+snoozeMinutes()*60000,dismissedAt:null};save();document.querySelector('.kairos-reminder-toast')?.remove();render()}
  function dismiss(id){state=load();const item=state.schedules.find(x=>x.id===id);if(item){item.reminder='none';item.updated_at=new Date().toISOString()}state.reminders=state.reminders||{};delete state.reminders[id];save();document.querySelector('.kairos-reminder-toast')?.remove();render();window.dispatchEvent(new CustomEvent('kairos:state-changed',{detail:state}));window.renderSchedules?.()}
  function openDetail(id){state.reminders[id]={...meta(id),dismissedAt:Date.now()};save();toggle(false);document.querySelector('.kairos-reminder-toast')?.remove();if(window.openScheduleFeature)window.openScheduleFeature(id);else location.href=`../schedule/index.html#schedule-${encodeURIComponent(id)}`;render()}
  function notify(item,missed=false){document.querySelector('.kairos-reminder-toast')?.remove();const node=document.createElement('aside');node.className='kairos-reminder-toast';node.innerHTML=`<button class="kairos-reminder-toast-close" aria-label="Dismiss reminder" title="Dismiss">×</button><strong>${missed?'Missed reminder':'Reminder'}: ${escape(item.title)}</strong><p>${escape(item.notes||timeText(item))}</p><div class="kairos-reminder-actions"><button data-done>Complete</button><button data-snooze>${escape(snoozeLabel())}</button><button data-open>Details</button></div>`;document.body.append(node);node.querySelector('.kairos-reminder-toast-close').onclick=()=>dismiss(item.id);node.querySelector('[data-done]').onclick=()=>complete(item.id);node.querySelector('[data-snooze]').onclick=()=>snooze(item.id);node.querySelector('[data-open]').onclick=()=>openDetail(item.id);clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.remove(),15000);if(desktopNotificationsEnabled())window.kairosDesktop?.reminders?.notify?.({scheduleId:item.id,title:item.title,note:item.notes||timeText(item),missed}).catch(()=>{});const bubble=document.createElement('div');bubble.className='kairos-pet-reminder';bubble.textContent=`桌宠: ${item.title} ${missed?'was missed':'is due now'}`;document.body.append(bubble);setTimeout(()=>bubble.remove(),6000);window.dispatchEvent(new CustomEvent('kairos:reminder',{detail:{item,missed}}))}
  function check(){state=load();const now=Date.now();for(const item of state.schedules){const m=meta(item.id),result=core.classifyReminder(item,m,now,GRACE,CHECK);if(result){state.reminders[item.id]={...m,firedAt:now,snoozedUntil:null};notify(item,result.missed)}}lastCheck=now;save();render()}
  function reset(){clearInterval(timer);check();timer=setInterval(check,CHECK)}
  const addDismissButtons=()=>{};
  document.head.insertAdjacentHTML('beforeend','<style>.kairos-reminder-head>[data-close],.kairos-reminder-dismiss,.kairos-reminder-toast-close{display:grid;width:40px;height:40px;padding:0;place-items:center;border:1px solid rgba(87,66,60,.12);border-radius:12px;background:rgba(238,233,220,.72);color:#57423c;font-size:24px;line-height:1;cursor:pointer;transition:transform .16s ease,background .16s ease}.kairos-reminder-head>[data-close]:hover,.kairos-reminder-dismiss:hover{transform:scale(1.04);background:#eee9dc}.kairos-reminder-item{position:relative;padding-right:50px}.kairos-reminder-dismiss,.kairos-reminder-toast-close{position:absolute;right:8px;top:8px;background:transparent}.kairos-reminder-toast-close{color:#fff;border-color:rgba(255,255,255,.14)}.kairos-reminder-toast-close:hover{transform:scale(1.04);background:rgba(255,255,255,.16)}.kairos-reminder-head>[data-close]:focus-visible,.kairos-reminder-dismiss:focus-visible,.kairos-reminder-toast-close:focus-visible{outline:3px solid rgba(209,99,60,.24);outline-offset:2px}</style>');
  document.addEventListener('click',event=>{const panelClose=event.target.closest?.('.kairos-reminder-panel [data-close]');if(panelClose){event.preventDefault();event.stopImmediatePropagation();toggle(false);return}const dismissButton=event.target.closest?.('.kairos-reminder-dismiss,.kairos-reminder-toast-close');if(dismissButton){event.preventDefault();event.stopImmediatePropagation();const id=dismissButton.dataset.dismiss||dismissButton.closest('.kairos-reminder-item')?.querySelector('[data-done]')?.dataset.done||pending()[0]?.id;if(id)dismiss(id);else dismissButton.closest('.kairos-reminder-toast')?.remove();return}const button=event.target.closest?.('[data-done]');if(!button||!button.closest('.kairos-reminder-panel,.kairos-reminder-toast'))return;event.preventDefault();event.stopImmediatePropagation();const id=button.dataset.done||pending()[0]?.id;if(id)complete(id)},true);
  ensureUI();state=load();const start=()=>{render();addDismissButtons();reset();window.addEventListener('focus',check);document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()});window.addEventListener('kairos:state-changed',()=>{state=load();render();check()});window.addEventListener('kairos:time-format-changed',render);window.addEventListener('kairos:reminder',event=>{const detail=event.detail||{};window.kairosDesktop?.pet?.react(detail.missed?'sleepy':'reminder',{title:detail.item?.title}).catch(()=>{})});window.addEventListener('pageshow',check)};if(window.kairosDesktop?.appState?.get){window.kairosDesktop.appState.get().then(next=>{state=next||state;start()}).catch(start)}else start();
})();
