import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { AiDataStore } from "../../services/ai/data-store.js";
import { AttachmentService } from "../../services/documents/attachments.js";
import { ToolRuntime } from "../../services/ai/tool-runtime.js";
import { AppStateStore, createAppAdapters } from "../../data/app-state/index.js";
import { ContextManager } from "../../services/ai/context-manager.js";
import { parseDocument } from "../../services/documents/document-parser.js";
import { MusicLibrary } from "../../services/music/music-library.js";
import { KairosAppDatabase } from "../../data/sqlite/index.js";
import { NeteaseApiService, normalizeNeteaseProfile, readableNeteasePlaybackMessage } from "../../services/music/netease-api-service.js";

async function fixture() { const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-test-"));const store=new AiDataStore(path.join(dir,"data.json"));return{dir,store}; }

test("conversation and messages persist",async()=>{const{dir,store}=await fixture();const c=await store.createConversation({title:"test"});await store.addMessage({conversationId:c.id,role:"user",content:"hello"});const loaded=await store.getConversation(c.id);assert.equal(loaded.title,"test");assert.equal(loaded.messages[0].content,"hello");await fs.rm(dir,{recursive:true,force:true});});

test.skip("AI data store restores conversations and memories from SQLite when JSON is missing or corrupt",async()=>{});

test.skip("NetEase API state restores login cookie from SQLite when JSON is missing or corrupt",async()=>{});

test("NetEase profile cache retains the sidebar identity fields only",()=>{assert.deepEqual(normalizeNeteaseProfile({userId:42,nickname:"Kairos",avatarUrl:"http://p1.music.126.net/avatar.jpg",extra:"ignored"}),{userId:42,nickname:"Kairos",avatarUrl:"https://p1.music.126.net/avatar.jpg"});assert.deepEqual(normalizeNeteaseProfile({account:{id:7,userName:"Account fallback"}}),{userId:7,nickname:"Account fallback",avatarUrl:""});assert.equal(normalizeNeteaseProfile({nickname:"Missing id"}),null);});

test("NetEase playback failures explain rights and unavailable URLs",()=>{assert.equal(readableNeteasePlaybackMessage({fee:1}),"This song requires NetEase membership or purchase.");assert.equal(readableNeteasePlaybackMessage({fee:4}),"This song requires NetEase membership or purchase.");assert.equal(readableNeteasePlaybackMessage({fee:8,payed:0}),"This song is restricted by NetEase rights.");assert.equal(readableNeteasePlaybackMessage({code:404}),"NetEase cannot provide a playable URL for this song.");assert.equal(readableNeteasePlaybackMessage({freeTrialInfo:{start:0}}),"This song is only available as a NetEase trial preview.");assert.equal(readableNeteasePlaybackMessage({message:"custom unavailable"}),"custom unavailable");assert.equal(readableNeteasePlaybackMessage({},"fallback unavailable"),"fallback unavailable");});

test("NetEase playback stays on the legacy EAPI client while downloads use the dedicated resolver",async()=>{
  const playbackCalls=[];
  let downloadCalls=0;
  const service=new NeteaseApiService({
    playbackApi:{
      song_detail:async input=>{playbackCalls.push(["detail",input]);return{body:{songs:[{id:100,name:"Song",ar:[{name:"Artist"}],al:{name:"Album"},dt:180000}]}};},
      song_url_v1:async input=>{playbackCalls.push(["url",input]);return{body:{data:[{id:100,url:"https://m10.music.126.net/song.mp3",time:180000,br:320000,level:"standard",expi:1200}]}};}
    },
    downloadUrlResolver:async()=>{downloadCalls++;return{code:200,data:[]};}
  });
  service.cookie="MUSIC_U=test-session";
  const result=await service.playSong({neteaseId:"100",level:"standard"});
  assert.equal(result.ok,true);
  assert.equal(result.track.playUrl,"https://m10.music.126.net/song.mp3");
  assert.deepEqual(playbackCalls.map(([kind])=>kind),["detail","url"]);
  assert.equal(playbackCalls.every(([,input])=>input.cookie==="MUSIC_U=test-session"),true);
  assert.equal(downloadCalls,0);
});

test("NetEase playlist collection coalesces writes and cools down after anti-abuse responses",async()=>{
  let calls=0;
  let clock=1_000;
  let mode="rate-limit";
  let rejectUpstream;
  const inputs=[];
  const requestClient=(uri,data,options)=>{
      calls++;
      inputs.push({uri,data,options});
      if(mode==="success")return Promise.resolve({status:200,body:{code:200}});
      return new Promise((_resolve,reject)=>{rejectUpstream=reject;});
  };
  const service=new NeteaseApiService({
    requestClient,
    now:()=>clock,
    t:(key,_params,fallback)=>key==="music.neteaseActionRateLimited"?"网易云提示操作过于频繁，请稍后再试。":fallback
  });
  service.cookie="MUSIC_U=test-session";
  service.requireProfile=async()=>({ok:true,profile:{userId:42}});

  const first=service.setPlaylistSubscribed({neteaseId:"123",subscribed:true});
  const duplicate=service.setPlaylistSubscribed({neteaseId:"123",subscribed:true});
  await new Promise(resolve=>setImmediate(resolve));
  rejectUpstream({status:405,body:{code:405,message:"鎿嶄綴杞囦粅棰ュ繁锛�请稍后再试"}});
  const [firstResult,duplicateResult]=await Promise.all([first,duplicate]);

  assert.equal(calls,1);
  assert.equal(firstResult.ok,false);
  assert.equal(firstResult.code,405);
  assert.equal(firstResult.message,"网易云提示操作过于频繁，请稍后再试。");
  assert.equal(firstResult.retryAfter,60_000);
  assert.deepEqual(duplicateResult,firstResult);
  assert.deepEqual(inputs,[{uri:"/api/playlist/subscribe",data:{id:"123"},options:{crypto:"weapi",cookie:"MUSIC_U=test-session"}}]);

  const cooledDown=await service.setPlaylistSubscribed({neteaseId:"456",subscribed:true});
  assert.equal(cooledDown.code,405);
  assert.equal(cooledDown.retryAfter,60_000);
  assert.equal(calls,1);

  clock+=60_000;
  mode="success";
  const success=await service.setPlaylistSubscribed({neteaseId:"456",subscribed:true});
  assert.equal(success.ok,true);
  assert.equal(success.subscribed,true);
  assert.equal(calls,2);
});

test("concurrent mutations use isolated temporary files and preserve every write",async()=>{const{dir,store}=await fixture();const items=await Promise.all(Array.from({length:20},(_,index)=>store.createConversation({title:`chat-${index}`})));assert.equal(items.length,20);assert.equal((await store.listConversations()).length,20);const tempFiles=await fs.readdir(dir);assert.equal(tempFiles.filter(name=>name.includes(".tmp")).length,0);await fs.rm(dir,{recursive:true,force:true});});

test("long-term memories persist and can be forgotten",async()=>{const{dir,store}=await fixture();const saved=await store.remember({type:"profile",key:"identity",value:"学生",confidence:.95});assert.equal((await store.listMemories())[0].value,"学生");await store.forgetMemory(saved.id);assert.equal((await store.listMemories()).length,0);await fs.rm(dir,{recursive:true,force:true});});

test("all long-term memories can be cleared at once",async()=>{const{dir,store}=await fixture();await store.remember({type:"profile",key:"identity",value:"学生"});await store.remember({type:"goal",key:"goal",value:"完成课程"});const result=await store.clearMemories();assert.equal(result.count,2);assert.equal((await store.listMemories()).length,0);await fs.rm(dir,{recursive:true,force:true});});

test("message attachment labels persist with the conversation",async()=>{const{dir,store}=await fixture();const c=await store.createConversation({title:"files"});await store.addMessage({conversationId:c.id,role:"user",content:"整理日程",attachmentIds:["a1"],attachmentNames:["课程表.png"]});const loaded=await store.getConversation(c.id);assert.deepEqual(loaded.messages[0].attachmentIds,["a1"]);assert.deepEqual(loaded.messages[0].attachmentNames,["课程表.png"]);await fs.rm(dir,{recursive:true,force:true});});

test("write proposal requires permission and explicit decision",async()=>{const{dir,store}=await fixture();const tools=new ToolRuntime(store);await assert.rejects(()=>tools.propose({conversationId:"c",domain:"tasks",operation:"create",payload:{title:"x"}}),/permission_denied/);await tools.setPermissions({tasks:"write"});const proposal=await tools.propose({conversationId:"c",domain:"tasks",operation:"create",payload:{title:"x"}});let calls=0;const result=await tools.decide({id:proposal.id,approved:true},{tasks:{create:async payload=>{calls++;return{id:"1",...payload};}}});assert.equal(calls,1);assert.equal(result.status,"committed");await fs.rm(dir,{recursive:true,force:true});});

test("external search permission is explicit and read-only",async()=>{const{dir,store}=await fixture();const tools=new ToolRuntime(store);assert.equal((await tools.getPermissions()).externalSearch,"none");await tools.setPermissions({externalSearch:"read"});assert.equal((await tools.getPermissions()).externalSearch,"read");await assert.rejects(()=>tools.setPermissions({externalSearch:"write"}),/invalid_permission/);await fs.rm(dir,{recursive:true,force:true});});

test("temporary attachments are cleaned",async()=>{const{dir,store}=await fixture();const service=new AttachmentService({rootDir:path.join(dir,"kept"),tempDir:path.join(dir,"temp"),store});const item=await service.save({conversationId:"c",name:"note.txt",mimeType:"text/plain",bytes:new TextEncoder().encode("ok"),retain:false});assert.equal(item.retain,false);await service.cleanupTemporary();assert.equal((await store.read()).attachments.length,0);await fs.rm(dir,{recursive:true,force:true});});

test("legacy localStorage state migrates only once",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-app-"));const store=new AppStateStore(path.join(dir,"app.json"));await store.initialize({schedules:[{id:"old",title:"legacy"}],theme:"dark"});await store.initialize({schedules:[{id:"overwrite"}]});const state=await store.read();assert.equal(state.schedules[0].id,"old");assert.equal(state.theme,"dark");await fs.rm(dir,{recursive:true,force:true});});

test("desktop app state persists user preferences with core data",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-app-settings-"));const store=new AppStateStore(path.join(dir,"app.json"));await store.initialize({settings:{appearance:{theme:"dark"},general:{language:"zh-CN"},ai:{replyStyle:"learning"}}});const state=await store.read();assert.equal(state.settings.appearance.theme,"dark");assert.equal(state.settings.general.language,"zh-CN");state.settings.appearance.theme="light";await store.write(state);const saved=await store.read();assert.equal(saved.settings.appearance.theme,"light");assert.equal(saved.settings.ai.replyStyle,"learning");await fs.rm(dir,{recursive:true,force:true});});

test("core schedules habits reminders and local music work without AI provider configuration",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-offline-core-"));const savedEnv={OPENAI_API_KEY:process.env.OPENAI_API_KEY,ARK_API_KEY:process.env.ARK_API_KEY,FIRECRAWL_API_KEY:process.env.FIRECRAWL_API_KEY};delete process.env.OPENAI_API_KEY;delete process.env.ARK_API_KEY;delete process.env.FIRECRAWL_API_KEY;try{const appStore=new AppStateStore(path.join(dir,"app-state.json"));await appStore.initialize({schedules:[],habits:[],settings:{ai:{provider:"none"}}});const adapters=createAppAdapters(appStore);const task=await adapters.tasks.create({title:"读书 30 分钟",date:"2026-07-13",type:"task",reminder:"30",status:"todo"});const event=await adapters.schedules.create({title:"健身房训练",date:"2026-07-13",type:"event",start_time:"16:00",end_time:"17:00",reminder:"10",status:"todo"});const habit=await adapters.habits.create({name:"阅读",icon:"book",dates:["2026-07-13"]});await adapters.tasks.update({id:task.id,status:"done"});const queriedTasks=await adapters.tasks.query({dateFrom:"2026-07-13",dateTo:"2026-07-13"});const queriedHabits=await adapters.habits.query({limit:10});assert.equal(queriedTasks[0].status,"done");assert.equal(queriedTasks[0].reminder,"30");assert.equal(queriedHabits[0].id,habit.id);const state=await appStore.read();assert.equal(state.schedules.find(item=>item.id===event.id).reminder,"10");assert.equal(state.settings.ai.provider,"none");const audio=path.join(dir,"offline.wav");await fs.writeFile(audio,Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});const imported=await library.addFiles([audio]);const trackId=imported.state.tracks[0].id;await library.updatePlayback({queueTrackIds:[trackId],currentTrackId:trackId,playing:true,volume:55});const musicState=await library.publicState();assert.equal(musicState.currentTrackId,trackId);assert.equal(musicState.playing,true);assert.equal(musicState.volume,55);}finally{if(savedEnv.OPENAI_API_KEY===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=savedEnv.OPENAI_API_KEY;if(savedEnv.ARK_API_KEY===undefined)delete process.env.ARK_API_KEY;else process.env.ARK_API_KEY=savedEnv.ARK_API_KEY;if(savedEnv.FIRECRAWL_API_KEY===undefined)delete process.env.FIRECRAWL_API_KEY;else process.env.FIRECRAWL_API_KEY=savedEnv.FIRECRAWL_API_KEY;await fs.rm(dir,{recursive:true,force:true});}});

test("confirmed task proposal writes into real schedule state",async()=>{const{dir,store:aiStore}=await fixture();const appStore=new AppStateStore(path.join(dir,"app-state.json"));await appStore.initialize({schedules:[]});const adapters=createAppAdapters(appStore);const tools=new ToolRuntime(aiStore);await tools.setPermissions({tasks:"write"});const proposal=await tools.propose({conversationId:"c",domain:"tasks",operation:"create",payload:{title:"概率论作业",date:"2026-06-21",type:"task"}});await tools.decide({id:proposal.id,approved:true},adapters);const state=await appStore.read();assert.equal(state.schedules.length,1);assert.equal(state.schedules[0].title,"概率论作业");await fs.rm(dir,{recursive:true,force:true});});

test("context limit requires an explicit decision",async()=>{const{dir,store}=await fixture();const manager=new ContextManager(store);const result=manager.assess({provider:"openai",limit:100,messages:[{role:"user",content:"很长的上下文".repeat(100)}]});assert.equal(result.requiresDecision,true);assert.deepEqual(result.options,["summarize","new_conversation"]);await fs.rm(dir,{recursive:true,force:true});});

test("new conversation can carry confirmed summary",async()=>{const{dir,store}=await fixture();const source=await store.createConversation({title:"原会话",provider:"openai",summary:"已确认摘要"});const next=await new ContextManager(store).createContinuation(source.id,{carrySummary:true});assert.equal(next.summary,"已确认摘要");assert.match(next.title,/Continue/);await fs.rm(dir,{recursive:true,force:true});});

test("plain text attachment keeps source location",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-doc-"));const file=path.join(dir,"note.txt");await fs.writeFile(file,"第一行\n第二行","utf8");const parsed=await parseDocument(file,"note.txt","text/plain");assert.equal(parsed.sections[0].location,"全文");assert.match(parsed.text,/第二行/);await fs.rm(dir,{recursive:true,force:true});});

test("deleting a conversation returns every related attachment for cleanup",async()=>{const{dir,store}=await fixture();const c=await store.createConversation();await store.mutate(data=>{data.attachments.push({id:"a",conversationId:c.id,path:path.join(dir,"a")},{id:"b",conversationId:c.id,path:path.join(dir,"b")});});const files=await store.deleteConversation(c.id);assert.equal(files.length,2);assert.equal((await store.read()).attachments.length,0);await fs.rm(dir,{recursive:true,force:true});});

test("music library imports supported local files and persists playback state",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-"));const audio=path.join(dir,"focus.wav");const note=path.join(dir,"note.txt");await fs.writeFile(audio,Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(note,"nope","utf8");const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});const result=await library.addFiles([audio,note,audio]);assert.equal(result.state.tracks.length,1);assert.equal(result.added.length,2);assert.equal(result.rejected[0].reason,"unsupported_format");assert.equal(result.state.tracks[0].title,"focus");assert.match(result.state.tracks[0].playUrl,/^file:/);await library.updatePlayback({queueTrackIds:[result.state.tracks[0].id],currentTrackId:result.state.tracks[0].id,mode:"loop",playing:true,volume:42,muted:true,position:{trackId:result.state.tracks[0].id,seconds:12}});const state=await library.publicState();assert.deepEqual(state.queueTrackIds,[result.state.tracks[0].id]);assert.equal(state.mode,"loop");assert.equal(state.playing,true);assert.equal(state.volume,42);assert.equal(state.muted,true);assert.equal(state.positions[result.state.tracks[0].id],12);await fs.rm(dir,{recursive:true,force:true});});

test("music runtime keeps source order when playback and source writes overlap",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-runtime-order-"));const statePath=path.join(dir,"music.json");const databasePath=path.join(dir,"kairos.sqlite");const firstDatabase=new KairosAppDatabase(databasePath);const first=new MusicLibrary({statePath,database:firstDatabase});await first.publicState();await Promise.all([first.updateRuntime({sourceOrder:["netease","local"]}),first.updateRuntime({lastSource:"local"}),first.updatePlayback({volume:33})]);const saved=await first.publicState();assert.deepEqual(saved.runtime.sourceOrder,["netease","local"]);assert.equal(saved.runtime.lastSource,"local");assert.equal(saved.volume,33);firstDatabase.close();const secondDatabase=new KairosAppDatabase(databasePath);const second=new MusicLibrary({statePath,database:secondDatabase});const restored=await second.publicState();assert.deepEqual(restored.runtime.sourceOrder,["netease","local"]);assert.equal(restored.runtime.lastSource,"local");assert.equal(restored.volume,33);secondDatabase.close();await fs.rm(dir,{recursive:true,force:true});});

test("music runtime persists NetEase recovery state across a fresh Electron service instance",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-runtime-"));const statePath=path.join(dir,"music.json");const databasePath=path.join(dir,"kairos.sqlite");const firstDatabase=new KairosAppDatabase(databasePath);const first=new MusicLibrary({statePath,coverDir:path.join(dir,"covers"),database:firstDatabase});const saved={tracks:[{id:"netease:42",title:"Source contract",artist:"Kairos",playUrl:"https://example.invalid/42"}],queueTrackIds:["netease:42"],currentTrackId:"netease:42",mode:"loop",positions:{"netease:42":37},updatedAt:"2026-08-03T00:00:00.000Z"};await first.updateRuntime({lastSource:"netease",neteasePlayback:saved,sidebarState:"collapsed",sourceOrder:["netease","local"]});firstDatabase.close();const secondDatabase=new KairosAppDatabase(databasePath);const second=new MusicLibrary({statePath,coverDir:path.join(dir,"covers"),database:secondDatabase});const state=await second.publicState();assert.equal(state.runtime.lastSource,"netease");assert.deepEqual(state.runtime.neteasePlayback,saved);assert.equal(state.runtime.sidebarState,"collapsed");assert.deepEqual(state.runtime.sourceOrder,["netease","local"]);secondDatabase.close();await fs.rm(dir,{recursive:true,force:true});});

test("music library rejects empty audio files without polluting the library",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-empty-"));const empty=path.join(dir,"empty.wav");const valid=path.join(dir,"valid.wav");await fs.writeFile(empty,Buffer.alloc(0));await fs.writeFile(valid,Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});const result=await library.addFiles([empty,valid]);assert.equal(result.rejected.length,1);assert.equal(result.rejected[0].reason,"empty_file");assert.equal(result.state.tracks.length,1);assert.equal(result.state.tracks[0].path,valid);assert.deepEqual(result.state.queueTrackIds,[]);assert.equal(result.state.currentTrackId,null);const persisted=await library.publicState();assert.equal(persisted.tracks.length,1);assert.equal(persisted.tracks[0].path,valid);assert.equal(persisted.tracks.some(track=>track.path===empty),false);await fs.rm(dir,{recursive:true,force:true});});

function id3SyncSafe(size){return Buffer.from([(size>>21)&0x7f,(size>>14)&0x7f,(size>>7)&0x7f,size&0x7f]);}
function id3Frame(id,body){const header=Buffer.alloc(10);header.write(id,0,4,"latin1");header.writeUInt32BE(body.length,4);return Buffer.concat([header,body]);}
function id3File(frames,audio=Buffer.from([1,2,3,4])){const tag=Buffer.concat(frames);return Buffer.concat([Buffer.from("ID3\u0003\u0000\u0000","latin1"),id3SyncSafe(tag.length),tag,audio]);}

test("music library skips oversized embedded covers and survives malformed tags",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-tags-"));const hugeCover=path.join(dir,"huge-cover.mp3");const malformed=path.join(dir,"broken-tags.mp3");const apic=Buffer.concat([Buffer.from([0]),Buffer.from("image/jpeg\u0000","latin1"),Buffer.from([3,0]),Buffer.alloc(5*1024*1024+1,7)]);await fs.writeFile(hugeCover,id3File([id3Frame("TIT2",Buffer.from([0,...Buffer.from("Huge Cover Track","latin1")])),id3Frame("APIC",apic)]));const badFrame=Buffer.alloc(10);badFrame.write("TIT2",0,4,"latin1");badFrame.writeUInt32BE(2048,4);await fs.writeFile(malformed,Buffer.concat([Buffer.from("ID3\u0003\u0000\u0000","latin1"),id3SyncSafe(badFrame.length),badFrame,Buffer.from([1,2,3])]));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});const result=await library.addFiles([hugeCover,malformed]);assert.equal(result.rejected.length,0);assert.equal(result.state.tracks.length,2);const huge=result.state.tracks.find(track=>track.path===hugeCover);const broken=result.state.tracks.find(track=>track.path===malformed);assert.equal(huge.title,"Huge Cover Track");assert.equal(huge.coverPath,"");assert.equal(broken.title,"broken-tags");assert.equal(broken.coverPath,"");const covers=await fs.readdir(path.join(dir,"covers")).catch(()=>[]);assert.equal(covers.length,0);await fs.rm(dir,{recursive:true,force:true});});

test("music library restores local queue and progress from SQLite when legacy JSON is unavailable",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-sqlite-restore-"));const statePath=path.join(dir,"music.json");const databasePath=path.join(dir,"kairos.sqlite");const audio=path.join(dir,"restore.wav");await fs.writeFile(audio,Buffer.from("RIFF....WAVEfmt "));const firstDatabase=new KairosAppDatabase(databasePath);const first=new MusicLibrary({statePath,database:firstDatabase});const imported=await first.addFiles([audio]);const id=imported.state.tracks[0].id;await first.updatePlayback({queueTrackIds:[id],currentTrackId:id,playing:true,mode:"shuffle",volume:61,muted:true,position:{trackId:id,seconds:27}});firstDatabase.close();await fs.rm(statePath,{force:true});const secondDatabase=new KairosAppDatabase(databasePath);const second=new MusicLibrary({statePath,database:secondDatabase});const restored=await second.publicState();assert.deepEqual(restored.queueTrackIds,[id]);assert.equal(restored.currentTrackId,id);assert.equal(restored.playing,true);assert.equal(restored.mode,"shuffle");assert.equal(restored.volume,61);assert.equal(restored.muted,true);assert.equal(restored.positions[id],27);secondDatabase.close();await fs.rm(dir,{recursive:true,force:true});});

test("music library imports a folder as a playlist",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-folder-"));const folder=path.join(dir,"LoFi Set");await fs.mkdir(path.join(folder,"disc1"),{recursive:true});await fs.writeFile(path.join(folder,"disc1","a.wav"),Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(path.join(folder,"b.mp3"),Buffer.from("ID3\u0004\u0000\u0000\u0000\u0000\u0000\u0000"));await fs.writeFile(path.join(folder,"cover.txt"),"skip","utf8");const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});const result=await library.addFolder(folder);assert.equal(result.tracks.length,2);assert.equal(result.playlists.length,1);assert.equal(result.playlists[0].name,"LoFi Set");assert.equal(result.playlists[0].trackIds.length,2);await fs.rm(dir,{recursive:true,force:true});});

test("music library import does not auto-create a playback queue",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-no-auto-queue-"));const folder=path.join(dir,"set");await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,"a.wav"),Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});const state=await library.addFolder(folder);assert.equal(state.tracks.length,1);assert.equal(state.queueTrackIds.length,0);assert.equal(state.currentTrackId,null);await fs.rm(dir,{recursive:true,force:true});});


test("music library can replace queue with a playlist",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-queue-"));const first=path.join(dir,"first");const second=path.join(dir,"second");await fs.mkdir(first,{recursive:true});await fs.mkdir(second,{recursive:true});await fs.writeFile(path.join(first,"a.wav"),Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(path.join(first,"b.wav"),Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(path.join(second,"c.wav"),Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});const one=await library.addFolder(first);const two=await library.addFolder(second);let state=await library.playPlaylist(one.playlist.id);assert.deepEqual(state.queueTrackIds,one.playlist.trackIds);assert.equal(state.currentTrackId,one.playlist.trackIds[0]);state=await library.playPlaylist(two.playlist.id);assert.deepEqual(state.queueTrackIds,two.playlist.trackIds);assert.equal(state.currentTrackId,two.playlist.trackIds[0]);assert.equal(state.tracks.length,3);await fs.rm(dir,{recursive:true,force:true});});

test("music library preserves playlist order while syncing folder changes",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-sync-"));const folder=path.join(dir,"set");await fs.mkdir(folder,{recursive:true});const a=path.join(folder,"a.wav");const b=path.join(folder,"b.wav");const c=path.join(folder,"c.wav");await fs.writeFile(a,Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(b,Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(c,Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let state=await library.addFolder(folder);const playlistId=state.playlist.id;const original=state.playlist.trackIds;state=await library.reorderPlaylist(playlistId,[original[2],original[0],original[1]]);assert.deepEqual(state.playlists[0].trackIds,[original[2],original[0],original[1]]);await fs.rm(b);const d=path.join(folder,"d.wav");await fs.writeFile(d,Buffer.from("RIFF....WAVEfmt "));state=await library.syncFolders();const synced=state.playlists[0].trackIds;assert.equal(synced.length,3);assert.equal(synced[0],original[2]);assert.equal(synced[1],original[0]);assert.ok(!synced.includes(original[1]));assert.equal(state.tracks.length,3);await fs.rm(dir,{recursive:true,force:true});});

test("music library reorder also updates playlist order",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-reorder-"));const folder=path.join(dir,"set");await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,"a.wav"),Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(path.join(folder,"b.wav"),Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(path.join(folder,"c.wav"),Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let state=await library.addFolder(folder);const ids=state.playlist.trackIds;state=await library.reorder([ids[2],ids[0],ids[1]]);assert.deepEqual(state.playlists[0].trackIds,[ids[2],ids[0],ids[1]]);await fs.rm(dir,{recursive:true,force:true});});

test("music library can clear playback queue without deleting tracks",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-clear-"));const folder=path.join(dir,"set");await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,"a.wav"),Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(path.join(folder,"b.wav"),Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let state=await library.addFolder(folder);assert.equal(state.tracks.length,2);state=await library.updatePlayback({queueTrackIds:[],currentTrackId:null});assert.equal(state.tracks.length,2);assert.equal(state.queueTrackIds.length,0);assert.equal(state.currentTrackId,null);await fs.rm(dir,{recursive:true,force:true});});

test("music library marks and removes missing local files",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-missing-"));const folder=path.join(dir,"set");await fs.mkdir(folder,{recursive:true});const first=path.join(folder,"a.wav");const second=path.join(folder,"b.wav");await fs.writeFile(first,Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(second,Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let state=await library.addFolder(folder);const missingId=state.tracks.find(track=>track.path===first).id;const keptId=state.tracks.find(track=>track.path===second).id;await library.updatePlayback({queueTrackIds:[missingId,keptId],currentTrackId:missingId,playing:true,position:{trackId:missingId,seconds:18}});await fs.rm(first);state=await library.publicState();const missing=state.tracks.find(track=>track.id===missingId);assert.equal(missing.available,false);assert.equal(missing.unavailableReason,"missing_file");state=await library.removeUnavailableTracks();assert.equal(state.removed.length,1);assert.equal(state.removed[0].id,missingId);assert.equal(state.tracks.some(track=>track.id===missingId),false);assert.deepEqual(state.queueTrackIds,[keptId]);assert.equal(state.currentTrackId,keptId);assert.equal(state.playing,true);assert.equal(state.positions[missingId],undefined);assert.equal(state.playlists[0].trackIds.includes(missingId),false);await fs.rm(dir,{recursive:true,force:true});});

test("music library removes a playlist from persistent state",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-remove-playlist-"));const folder=path.join(dir,"set");await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,"a.wav"),Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let state=await library.addFolder(folder);assert.equal(state.playlists.length,1);state=await library.removePlaylist(state.playlist.id);assert.equal(state.playlists.length,0);const persisted=await library.publicState();assert.equal(persisted.playlists.length,0);await fs.rm(dir,{recursive:true,force:true});});

test("music library hides and restores playlist tracks",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-hide-track-"));const folder=path.join(dir,"set");await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,"a.wav"),Buffer.from("RIFF....WAVEfmt "));await fs.writeFile(path.join(folder,"b.wav"),Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let state=await library.addFolder(folder);const playlistId=state.playlist.id;const [first,second]=state.playlist.trackIds;state=await library.removeTracksFromPlaylist(playlistId,[first]);assert.deepEqual(state.playlists[0].trackIds,[second]);assert.equal(state.playlists[0].hiddenTrackPaths.length,1);state=await library.refreshPlaylist(playlistId);assert.deepEqual(state.playlists[0].trackIds,[second]);state=await library.restoreHiddenTracks(playlistId,state.playlists[0].hiddenTrackPaths);assert.equal(state.playlists[0].trackIds.length,2);await fs.rm(dir,{recursive:true,force:true});});

test("music library persists liked tracks",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-like-"));const audio=path.join(dir,"like.wav");await fs.writeFile(audio,Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let result=await library.addFiles([audio]);const trackId=result.state.tracks[0].id;let state=await library.updateTrack({id:trackId,liked:true});assert.equal(state.tracks[0].liked,true);assert.ok(state.tracks[0].likedAt);state=await library.updateTrack({id:trackId,liked:false});assert.equal(state.tracks[0].liked,false);assert.equal(state.tracks[0].likedAt,null);await fs.rm(dir,{recursive:true,force:true});});

test("music library removes a NetEase download, its file, and active playback together",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-download-remove-"));const downloadDir=path.join(dir,"Kairos Downloads");await fs.mkdir(downloadDir,{recursive:true});const audio=path.join(downloadDir,"Artist - Song [100].mp3");await fs.writeFile(audio,Buffer.from("ID3\u0004\u0000\u0000\u0000\u0000\u0000\u0000"));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let state=await library.upsertDownloadedTrack({filePath:audio,source:{neteaseId:"100",title:"Song",artist:"Artist",album:"Album",requestedQuality:"standard",resolvedQuality:"standard"}});const track=state.tracks[0];await library.updatePlayback({queueTrackIds:[track.id],currentTrackId:track.id,playing:true,position:{trackId:track.id,seconds:12}});state=await library.removeDownloadedTrack(track.id,{downloadDir});assert.equal(state.tracks.length,0);assert.deepEqual(state.queueTrackIds,[]);assert.equal(state.currentTrackId,null);assert.equal(state.playing,false);assert.equal(state.positions[track.id],undefined);await assert.rejects(fs.access(audio));await fs.rm(dir,{recursive:true,force:true});});

test("music library persists play counts",async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),"kairos-music-plays-"));const audio=path.join(dir,"played.wav");await fs.writeFile(audio,Buffer.from("RIFF....WAVEfmt "));const library=new MusicLibrary({statePath:path.join(dir,"music.json"),coverDir:path.join(dir,"covers")});let result=await library.addFiles([audio]);const trackId=result.state.tracks[0].id;let state=await library.updateTrack({id:trackId,incrementPlayCount:true});assert.equal(state.tracks[0].playCount,1);assert.ok(state.tracks[0].lastPlayedAt);state=await library.updateTrack({id:trackId,incrementPlayCount:true});assert.equal(state.tracks[0].playCount,2);await fs.rm(dir,{recursive:true,force:true});});
