const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const root = path.resolve(__dirname, '..');
const validation = spawnSync(process.execPath, [path.join(__dirname, 'validate-i18n.cjs')], { stdio: 'inherit' });
if (validation.status !== 0) process.exit(validation.status || 1);

const locales = Object.fromEntries(['en', 'zh-CN'].map(locale => {
  const file = path.join(root, 'app', 'i18n', 'locales', locale + '.json');
  return [locale, JSON.parse(fs.readFileSync(file, 'utf8'))];
}));
const output = '/* Generated by scripts/build-i18n.cjs. Do not edit directly. */\n' +
  'window.KairosI18nMessages = Object.freeze(' + JSON.stringify(locales, null, 2) + ');\n';
fs.writeFileSync(path.join(root, 'app', 'i18n', 'i18n-messages.js'), output, 'utf8');
console.log('Generated app/i18n/i18n-messages.js');
