(() => {
  const KEY='kairos-mvp-state';
  const calendarCore=window.KairosCalendarCore;
  const todayKey=()=>calendarCore?.dateKey?.()||(()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`})();
  const normalizeSchedules=input=>({...input,schedules:Array.isArray(input?.schedules)?input.schedules:[]});
  let bootstrapConsumed=false;
  const readStore=store=>{try{return normalizeSchedules(JSON.parse(store?.getItem(KEY)||'{}'))}catch{return {schedules:[]}}};
  const load=()=>{const local=readStore(localStorage);try{const urlState=new URLSearchParams(location.search).get('scheduleState');if(urlState&&!bootstrapConsumed){bootstrapConsumed=true;return mergeState(normalizeSchedules(JSON.parse(urlState)),local)}if(window.name?.startsWith('kairos-state:')&&!bootstrapConsumed){bootstrapConsumed=true;const bootstrap=normalizeSchedules(JSON.parse(window.name.slice(13)||'{}'));window.name='';return mergeState(bootstrap,local)}if(window.top!==window){const shared=readStore(window.top.localStorage);return mergeState(shared,local)}}catch{}return local};
  let state=load(), selected=todayKey(), editing=null, undoTimer, calendarView=new Date(new Date().getFullYear(),new Date().getMonth(),1),monthMotionDirection=1,monthWheelAccumulator=0,monthWheelLocked=false,monthWheelReset,quietSaveUntil=0;
  function mergeState(primary={},fallback={}){
    primary=normalizeSchedules(primary);fallback=normalizeSchedules(fallback);
    const merged={...fallback,...primary};
    if(!primary.schedules.length&&fallback.schedules.length)merged.schedules=fallback.schedules;
    return normalizeSchedules(merged);
  }
  const postState=target=>{try{target?.postMessage({type:'kairos:state-sync',state},'*')}catch{}};
  const broadcastState=()=>{if(window.top!==window)postState(window.top);else document.querySelectorAll('iframe.kairos-spa-view').forEach(frame=>postState(frame.contentWindow))};
  const reactPet=(action,payload={})=>{if(window.kairosDesktop?.pet?.react)return window.kairosDesktop.pet.react(action,payload).catch(()=>{});if(window.top!==window)window.top.postMessage({type:'kairos:pet-react',action,payload},'*')};
  const save=()=>{const serialized=JSON.stringify(state);localStorage.setItem(KEY,serialized);window.dispatchEvent(new CustomEvent('kairos:state-changed',{detail:state}));try{if(window.top!==window){window.top.localStorage.setItem(KEY,serialized);window.top.dispatchEvent(new CustomEvent('kairos:state-changed',{detail:state}))}else document.querySelectorAll('iframe.kairos-spa-view').forEach(frame=>frame.contentWindow?.dispatchEvent(new CustomEvent('kairos:state-changed',{detail:state}))) }catch{}broadcastState();window.kairosDesktop?.appState.save(state).catch(console.error)};
  const saveQuiet=()=>{quietSaveUntil=Date.now()+800;const serialized=JSON.stringify(state);localStorage.setItem(KEY,serialized);try{if(window.top!==window)window.top.localStorage.setItem(KEY,serialized)}catch{}broadcastState();window.kairosDesktop?.appState.save(state).catch(console.error)};
  const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now();
  const dateKey=date=>calendarCore?.dateKey?.(date)||`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  const fromDateKey=key=>calendarCore?.fromDateKey?.(key)||(()=>{const [year,month,day]=String(key).split('-').map(Number);return new Date(year,month-1,day)})();
  const monthGrid=(year,monthIndex)=>calendarCore?.monthGrid?.(year,monthIndex)||(()=>{const first=new Date(year,monthIndex,1),start=new Date(year,monthIndex,1-first.getDay());return Array.from({length:42},(_,i)=>{const date=new Date(start.getFullYear(),start.getMonth(),start.getDate()+i),key=dateKey(date);return{key,year:date.getFullYear(),monthIndex:date.getMonth(),day:date.getDate(),weekday:date.getDay(),inMonth:date.getMonth()===monthIndex,isToday:key===todayKey()}})})();
  const dateWeekday=date=>calendarCore?.weekday?.(date)??(()=>{const [year,month,day]=String(date).split('-').map(Number);return new Date(year,month-1,day).getDay()})();
  const legacyWeekdays=x=>{
    const recurrence=x.recurrence;
    if(recurrence?.frequency==='weekly'&&Array.isArray(recurrence.weekdays)&&recurrence.weekdays.length)return new Set(recurrence.weekdays.map(Number));
    const text=`${x.cadence||''} ${x.notes||''}`;
    const map={日:0,天:0,一:1,二:2,三:3,四:4,五:5,六:6};const values=[...text.matchAll(/每(?:周|星期)\s*([日天一二三四五六])/g)].map(match=>map[match[1]]).filter(value=>value!==undefined);
    return values.length?new Set(values):null;
  };
  const covers=(x,date)=>calendarCore?.coversDate?.(x,date)??(()=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(x.date||''))return false;const end=x.recurrence?.until&&x.recurrence.until<(x.end_date||x.date)?x.recurrence.until:(x.end_date||x.date);if(!/^\d{4}-\d{2}-\d{2}$/.test(end)||x.date>date||end<date)return false;const weekdays=legacyWeekdays(x);return !weekdays||weekdays.has(dateWeekday(date))})();
  const timeForDate=(item,date)=>calendarCore?.timeForDate?.(item,date)||(()=>{const end=item.end_date||item.date;if(item.all_day)return'All day';if(item.date<date&&date<end)return'All day';if(date===end&&end!==item.date)return item.end_time?`Until ${item.end_time}`:'All day';return item.start_time||'TBD'})();
  const sortTimeForDate=(item,date)=>calendarCore?.sortTimeForDate?.(item,date)||(()=>{const label=timeForDate(item,date);return label==='All day'||label.startsWith('Until ')?'00:00':item.start_time||'99:99'})();
  const status=x=>{if(x.status==='done')return'done';const end=`${x.end_date||x.date}T${x.all_day?'23:59':x.end_time||x.start_time||'23:59'}`;return end<new Date().toISOString().slice(0,16)?'overdue':x.status||'todo'};
  const labels={task:'Task',deadline:'Deadline',event:'Event',match:'Match',holiday:'Holiday',other:'Other',todo:'To Do',doing:'In Progress',done:'Completed',overdue:'Overdue',high:'High',medium:'Medium',low:'Low'};
  const readSettings=()=>{try{return window.KairosSettingsFeature?.read?.()||window.top?.KairosSettingsFeature?.read?.()||JSON.parse((window.top||window).localStorage.getItem('kairos-settings')||'{}')}catch{return {}}};
  const defaultReminderForType=type=>window.KairosReminderCore?.defaultReminderForType?.(type,readSettings()?.reminders)||({deadline:'1440',event:'30',match:'30'}[type]||'none');
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const minutesOf=time=>{const match=String(time||'').match(/^(\d{2}):(\d{2})$/);return match?Number(match[1])*60+Number(match[2]):null};
  const scheduleRange=item=>{if(!item||item.all_day||!item.date||!item.start_time||!item.end_time)return null;const start=minutesOf(item.start_time),end=minutesOf(item.end_time);return start==null||end==null||end<=start?null:{date:item.date,start,end}};
  const conflictingSchedules=item=>{const range=scheduleRange(item);if(!range)return[];return state.schedules.filter(current=>current.id!==item.id&&status(current)!=='done').filter(current=>{const other=scheduleRange(current);return other&&other.date===range.date&&other.start<range.end&&range.start<other.end})};
  const dayDelta=(from,to)=>Math.round((fromDateKey(to)-fromDateKey(from))/86400000);
  const shiftDate=(date,days)=>dateKey(new Date(fromDateKey(date).getFullYear(),fromDateKey(date).getMonth(),fromDateKey(date).getDate()+days));
  const moveScheduleToDate=(id,targetDate)=>{const item=state.schedules.find(row=>row.id===id);if(!item||!targetDate||item.date===targetDate)return false;const span=Math.max(0,dayDelta(item.date,item.end_date||item.date)),oldDate=item.date;item.date=targetDate;item.end_date=shiftDate(targetDate,span);if(item.recurrence?.until)item.recurrence={...item.recurrence,until:shiftDate(item.recurrence.until,dayDelta(oldDate,targetDate))};item.updated_at=new Date().toISOString();save();renderAll();return true};
  const shiftedTimeRange=(item,delta)=>calendarCore?.shiftTimeRange?.(item.start_time,item.end_time||item.start_time,delta)||(()=>{const start=minutesOf(item.start_time),end=minutesOf(item.end_time||item.start_time);if(start==null||end==null)return null;const duration=Math.max(15,end-start||60),nextStart=Math.max(0,Math.min(1439-duration,start+delta));return{start_time:`${String(Math.floor(nextStart/60)).padStart(2,'0')}:${String(nextStart%60).padStart(2,'0')}`,end_time:`${String(Math.floor((nextStart+duration)/60)).padStart(2,'0')}:${String((nextStart+duration)%60).padStart(2,'0')}`}})();
  const shiftScheduleTime=(id,delta=15)=>{const item=state.schedules.find(row=>row.id===id);if(!item||item.all_day||!item.start_time)return false;const next=shiftedTimeRange(item,delta);if(!next)return false;const old={...item};Object.assign(item,next,{updated_at:new Date().toISOString()});saveQuiet();renderToday();calendarPage();toast(`Time updated to ${item.start_time}`,'Undo',()=>{Object.assign(item,old,{updated_at:new Date().toISOString()});save();renderAll();toast('Schedule restored')});return true};
  const kairosConfirmAlert=({title,description,action='Continue',cancel='Cancel',tone='danger'}={})=>new Promise(resolve=>{
    let dialog=document.getElementById('kairosAlertDialog');
    if(!dialog){dialog=document.createElement('dialog');dialog.id='kairosAlertDialog';dialog.className='kairos-alert-dialog';dialog.setAttribute('role','alertdialog');dialog.innerHTML='<form method="dialog" class="kairos-alert-content"><div class="kairos-alert-header"><div class="kairos-alert-media"><span class="material-symbols-outlined">warning</span></div><div><h2 class="kairos-alert-title"></h2><p class="kairos-alert-description"></p></div></div><footer class="kairos-alert-footer"><button class="kairos-alert-cancel" value="cancel" type="submit"></button><button class="kairos-alert-action" value="confirm" type="submit"></button></footer></form>';document.body.append(dialog)}
    dialog.dataset.tone=tone;dialog.querySelector('.kairos-alert-title').textContent=title||'Are you sure?';dialog.querySelector('.kairos-alert-description').textContent=description||'This action cannot be undone.';dialog.querySelector('.kairos-alert-cancel').textContent=cancel;dialog.querySelector('.kairos-alert-action').textContent=action;
    const done=value=>{dialog.removeEventListener('close',onClose);resolve(value)};const onClose=()=>done(dialog.returnValue==='confirm');
    dialog.addEventListener('close',onClose,{once:true});dialog.showModal();dialog.querySelector('.kairos-alert-cancel')?.focus();
  });
  const toast=(text,action,fn,placement='bottom')=>{let n=document.querySelector('.schedule-toast');if(!n){n=document.createElement('div');n.className='schedule-toast';document.body.append(n)}n.classList.toggle('schedule-toast-top-right',placement==='top-right');n.innerHTML=`<span>${escape(text)}</span>${action?`<button style="background:transparent!important;background-color:transparent!important;background-image:none!important;border-color:transparent!important;box-shadow:none!important">${escape(action)}</button>`:''}`;n.querySelector('button')?.addEventListener('click',fn);n.classList.add('show');clearTimeout(undoTimer);undoTimer=setTimeout(()=>n.classList.remove('show'),action?5000:1800)};
  function ensureDialog(){if(document.getElementById('scheduleFeatureDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog class="schedule-dialog" id="scheduleFeatureDialog"><form class="schedule-form" id="scheduleFeatureForm"><div class="schedule-form-head"><h2>添加日程与任务</h2><button type="button" data-close>×</button></div><div class="schedule-form-grid"><label class="schedule-field full">标题<input name="title" required></label><label class="schedule-field">类型<select name="type"><option value="task">任务</option><option value="deadline">Deadline</option><option value="event">事件</option><option value="match">比赛</option><option value="holiday">节日</option><option value="other">其他</option></select></label><label class="schedule-field">优先级<select name="priority"><option value="medium">中</option><option value="high">高</option><option value="low">低</option></select></label><label class="schedule-field">开始日期<input name="date" type="date" required></label><label class="schedule-field">结束日期<input name="end_date" type="date" required></label><label class="schedule-field full schedule-all-day"><input name="all_day" type="checkbox">全天安排</label><label class="schedule-field time">开始时间<input name="start_time" type="time"></label><label class="schedule-field time">结束时间<input name="end_time" type="time"></label><label class="schedule-field">提醒<select name="reminder"><option value="none">不提醒</option><option value="0">准时</option><option value="10">提前 10 分钟</option><option value="30">提前 30 分钟</option><option value="60">提前 1 小时</option><option value="1440">提前 1 天</option></select></label><label class="schedule-field">状态<select name="status"><option value="todo">待办</option><option value="doing">进行中</option><option value="done">已完成</option></select></label><label class="schedule-field full">备注<textarea name="notes" rows="3"></textarea></label></div><div class="schedule-dialog-actions"><button class="schedule-danger" type="button" data-delete>删除</button><button type="button" data-close>取消</button><button class="schedule-primary" type="submit">保存</button></div></form></dialog>`);
    const d=document.getElementById('scheduleFeatureDialog'),f=d.querySelector('form');
    const conflictPreview=document.createElement('div');conflictPreview.className='schedule-conflict-preview';conflictPreview.hidden=true;conflictPreview.setAttribute('role','status');f.querySelector('.schedule-dialog-actions').before(conflictPreview);
    const renderConflictPreview=()=>{const draft=Object.fromEntries(new FormData(f));draft.id=editing||'';draft.all_day=f.all_day.checked;const conflicts=conflictingSchedules(draft);conflictPreview.hidden=!conflicts.length;if(!conflicts.length){conflictPreview.textContent='';return}const names=conflicts.slice(0,3).map(item=>escape(item.title||'Untitled schedule')).join(', '),remaining=conflicts.length-3;conflictPreview.innerHTML=`<span class="material-symbols-outlined" aria-hidden="true">warning</span><span>Overlaps with ${names}${remaining>0?` and ${remaining} more`:''}.</span>`};d._renderConflictPreview=renderConflictPreview;
    const fieldNames={title:'Title',type:'Type',priority:'Priority',date:'Start Date',end_date:'End Date',start_time:'Start Time',end_time:'End Time',reminder:'Reminder',status:'Status',notes:'Notes'};
    Object.entries(fieldNames).forEach(([name,text])=>{const label=f.elements[name]?.closest('label');if(label?.firstChild)label.firstChild.nodeValue=text});
    f.querySelector('.schedule-all-day').lastChild.nodeValue=' All-day schedule';
    const optionCopy={task:'Task',deadline:'Deadline',event:'Event',match:'Match',holiday:'Holiday',other:'Other',medium:'Medium',high:'High',low:'Low',none:'No reminder','0':'At start time','10':'10 minutes before','30':'30 minutes before','60':'1 hour before','1440':'1 day before',todo:'To Do',doing:'In Progress',done:'Completed'};
    f.querySelectorAll('option').forEach(option=>{if(optionCopy[option.value])option.textContent=optionCopy[option.value]});
    d.querySelector('.schedule-form-head h2').textContent='Add Schedule';
    d.querySelector('[data-delete]').textContent='Delete';
    const dialogButtons=d.querySelectorAll('.schedule-dialog-actions button');dialogButtons[1].textContent='Cancel';dialogButtons[2].textContent='Save';
    d.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();editing=null;d.close()}));
    setupRangePicker(d,f);
    setupScheduleComboboxes(d,f);
    setupCounterTimePicker(d,f);
    f.addEventListener('input',renderConflictPreview);f.addEventListener('change',renderConflictPreview);
    f.all_day.onchange=()=>d.querySelectorAll('.time').forEach(x=>{x.style.opacity=f.all_day.checked?'.4':'1';x.querySelector('input').disabled=f.all_day.checked;x.classList.toggle('time-disabled',f.all_day.checked)});
    f.type.onchange=()=>{if(f.reminder.value==='none'&&!editing)f.reminder.value=defaultReminderForType(f.type.value)};
    f.onsubmit=async e=>{e.preventDefault();const old=state.schedules.find(x=>x.id===editing),data=Object.fromEntries(new FormData(f));data.id=editing||uid();data.all_day=f.all_day.checked;data.created_at=old?.created_at||new Date().toISOString();data.updated_at=new Date().toISOString();data.source=old?.source||'manual';if(data.end_date<data.date)return toast('The end date cannot be earlier than the start date.');if(!data.all_day&&data.date===data.end_date&&data.start_time&&data.end_time<data.start_time)return toast('The end time cannot be earlier than the start time.');const conflicts=conflictingSchedules(data);if(conflicts.length){const ok=await kairosConfirmAlert({title:'Schedule time conflict?',description:`${conflicts.length} existing schedule${conflicts.length===1?'':'s'} overlap this time. Save anyway?`,action:'Save Anyway',cancel:'Review',tone:'warning'});if(!ok)return}state.schedules=editing?state.schedules.map(x=>x.id===editing?data:x):[...state.schedules,data];save();d.close();renderAll();toast('Schedule saved')};
    d.querySelector('[data-delete]').onclick=async()=>{if(!editing)return;const ok=await kairosConfirmAlert({title:'Delete schedule?',description:'This schedule will be removed from your calendar. You can still undo it right after deletion.',action:'Delete',cancel:'Cancel'});if(!ok)return;const old=state.schedules.find(x=>x.id===editing);state.schedules=state.schedules.filter(x=>x.id!==editing);save();d.close();renderAll();toast('Schedule deleted','Undo',()=>{state.schedules.push(old);save();renderAll();toast('Schedule restored')})};
  }
  function open(item){ensureDialog();editing=item?.id||null;const d=document.getElementById('scheduleFeatureDialog'),f=d.querySelector('form');f.reset();const type=item?.type||'task';for(const k of ['title','type','priority','date','end_date','start_time','end_time','reminder','status','notes'])if(f[k])f[k].value=item?.[k]??({date:selected,end_date:selected,type,priority:'medium',reminder:defaultReminderForType(type),status:'todo'}[k]??'');f.all_day.checked=!!item?.all_day;f.all_day.dispatchEvent(new Event('change'));d.querySelector('h2').textContent=item?'Edit Schedule':'Add Schedule';d.querySelector('[data-delete]').style.visibility=item?'visible':'hidden';d.showModal();d._simpleTypePicker?.sync();d._rangePicker?.sync();d._renderConflictPreview?.()}
  function setupRangePicker(dialog,form){
    const dateField=form.date.closest('.schedule-field'),endField=form.end_date.closest('.schedule-field');dateField.classList.add('schedule-date-native');endField.classList.add('schedule-date-native');
    const field=document.createElement('div');field.className='schedule-field full schedule-range-field';field.innerHTML='<span>Date range</span><button class="schedule-range-trigger" type="button"><span class="material-symbols-outlined">calendar_month</span><span data-range-label>Select a date range</span></button><section class="schedule-range-popover" hidden><header><button type="button" data-range-prev>‹</button><strong>Select a date range</strong><button type="button" data-range-next>›</button></header><div class="schedule-range-months"></div></section>';dateField.before(field);
    let view=new Date(),from='',to='';const label=field.querySelector('[data-range-label]'),popover=field.querySelector('.schedule-range-popover'),months=field.querySelector('.schedule-range-months'),key=dateKey,parse=fromDateKey,pretty=s=>new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric'}).format(parse(s));
    const paint=()=>{label.textContent=from?(to&&to!==from?`${pretty(from)} — ${pretty(to)}`:pretty(from)):'Select a date range';months.innerHTML='';for(let offset=0;offset<2;offset++){const base=new Date(view.getFullYear(),view.getMonth()+offset,1),box=document.createElement('div');box.className='schedule-range-month';box.innerHTML=`<h4>${base.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h4><div class="schedule-range-week"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="schedule-range-days"></div>`;const days=box.querySelector('.schedule-range-days');monthGrid(base.getFullYear(),base.getMonth()).forEach(day=>{const d=fromDateKey(day.key),k=key(d),b=document.createElement('button');b.type='button';b.textContent=day.day;b.className=(!day.inMonth?'outside ':'')+(k===from||k===to?'edge ':'')+(from&&to&&k>from&&k<to?'in-range ':'');b.onclick=()=>{if(!from||(from&&to)){from=k;to=''}else if(k<from){to=from;from=k}else to=k;form.date.value=from;form.end_date.value=to||from;paint();if(to)popover.hidden=true};days.append(b)});months.append(box)}};
    field.querySelector('.schedule-range-trigger').onclick=()=>{popover.hidden=!popover.hidden;if(!popover.hidden)paint()};field.querySelector('[data-range-prev]').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1);paint()};field.querySelector('[data-range-next]').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);paint()};dialog._rangePicker={sync(){from=form.date.value;to=form.end_date.value||from;view=from?new Date(parse(from).getFullYear(),parse(from).getMonth(),1):new Date();popover.hidden=true;paint()}};
  }
  function setupScheduleComboboxes(dialog,form){
    const selects=[form.type,form.reminder,form.status].filter(Boolean);
    const syncers=[];
    selects.forEach(select=>{
      if(select.dataset.comboboxReady)return;
      select.dataset.comboboxReady='true';
      const field=select.closest('.schedule-field');field.classList.add('kairos-combobox-field');
      const root=document.createElement('div');root.className='kairos-combobox';root.dataset.name=select.name;
      root.innerHTML='<button class="kairos-combobox-input" type="button" role="combobox" aria-haspopup="listbox" aria-expanded="false"><span></span><i class="material-symbols-outlined">expand_more</i></button><section class="kairos-combobox-content" hidden><div class="kairos-combobox-empty" hidden>No items found.</div><div class="kairos-combobox-list" role="listbox"></div></section>';
      select.after(root);
      const trigger=root.querySelector('.kairos-combobox-input'),valueLabel=trigger.querySelector('span'),content=root.querySelector('.kairos-combobox-content'),list=root.querySelector('.kairos-combobox-list'),empty=root.querySelector('.kairos-combobox-empty');
      const options=()=>[...select.options].map(option=>({value:option.value,label:option.textContent||option.value}));
      const close=()=>{content.hidden=true;trigger.setAttribute('aria-expanded','false')};
      const closeOthers=()=>dialog.querySelectorAll('.kairos-combobox-content,.counter-time-popover,.simple-type-popover').forEach(node=>{if(node!==content)node.hidden=true});
      const paint=()=>{const current=select.selectedOptions[0]?.textContent||'';valueLabel.textContent=current;list.innerHTML='';const rows=options();empty.hidden=!!rows.length;rows.forEach(item=>{const button=document.createElement('button');button.type='button';button.className='kairos-combobox-item';button.dataset.value=item.value;button.setAttribute('role','option');button.setAttribute('aria-selected',String(item.value===select.value));button.innerHTML=`<span>${escape(item.label)}</span><i class="material-symbols-outlined">check</i>`;list.append(button)})};
      const open=()=>{closeOthers();content.hidden=false;trigger.setAttribute('aria-expanded','true');paint()};
      trigger.onclick=event=>{event.preventDefault();content.hidden?open():close()};
      trigger.onkeydown=event=>{if(!['ArrowDown','ArrowUp','Enter',' '].includes(event.key))return;event.preventDefault();if(content.hidden){open();return}const all=options(),index=all.findIndex(item=>item.value===select.value),next=event.key==='ArrowUp'?all[(index-1+all.length)%all.length]:all[(index+1)%all.length];if(next){select.value=next.value;select.dispatchEvent(new Event('change',{bubbles:true}));paint()}};
      list.onclick=event=>{const item=event.target.closest('.kairos-combobox-item');if(!item)return;select.value=item.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));paint();close();trigger.focus()};
      select.addEventListener('change',paint);
      syncers.push(paint);paint();
    });
    dialog.addEventListener('click',event=>{if(event.target.closest('.kairos-combobox'))return;dialog.querySelectorAll('.kairos-combobox-content').forEach(node=>node.hidden=true)},true);
    dialog._simpleTypePicker={sync(){syncers.forEach(fn=>fn())}};
  }
  function setupCounterTimePicker(dialog,form){
    const pad=n=>String(n).padStart(2,'0'),minutes=[0,5,10,15,20,25,30,35,40,45,50,55];
    const closeAll=except=>dialog.querySelectorAll('.counter-time-popover').forEach(p=>{if(p!==except)p.hidden=true});
    const clampMinute=value=>minutes.reduce((best,n)=>Math.abs(n-value)<Math.abs(best-value)?n:best,0);
    const setup=input=>{
      const label=input.closest('.schedule-field'),name=input.name;
      label.classList.add('counter-time-field');
      input.classList.add('counter-time-native');
      input.tabIndex=-1;
      const trigger=document.createElement('button');
      trigger.type='button';trigger.className='counter-time-trigger';trigger.innerHTML='<span class="counter-time-display">--:--</span><span class="material-symbols-outlined">schedule</span>';
      const popover=document.createElement('section');
      popover.className='counter-time-popover';popover.hidden=true;
      popover.innerHTML='<div class="counter-time-frame"><div class="counter-time-column" data-part="hour"></div><div class="counter-time-separator">:</div><div class="counter-time-column" data-part="minute"></div></div><div class="counter-time-footer"><button type="button" data-clear>Clear</button><button type="button" data-now>Now</button></div>';
      input.after(trigger,popover);
      const display=trigger.querySelector('.counter-time-display'),hourCol=popover.querySelector('[data-part="hour"]'),minuteCol=popover.querySelector('[data-part="minute"]');
      let hour=9,minute=0;
      const parse=()=>{const match=(input.value||'').match(/^(\d{2}):(\d{2})/);if(match){hour=Math.min(23,Math.max(0,+match[1]));minute=clampMinute(+match[2])}};
      const option=(value,current,part)=>`<button type="button" class="counter-time-number ${value===current?'is-active':''}" data-part="${part}" data-value="${value}"><span>${pad(value)}</span></button>`;
      const windowValues=(current,max,step=1)=>[-2,-1,0,1,2].map(offset=>(current+offset*step+max+1)%(max+1));
      const paint=()=>{parse();display.textContent=input.value||'--:--';hourCol.innerHTML=windowValues(hour,23).map(v=>option(v,hour,'hour')).join('');minuteCol.innerHTML=[-2,-1,0,1,2].map(offset=>minutes[(minutes.indexOf(minute)+offset+minutes.length)%minutes.length]).map(v=>option(v,minute,'minute')).join('')};
      const commit=()=>{input.value=`${pad(hour)}:${pad(minute)}`;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));paint();if(name==='start_time'&&form.end_time&&!form.end_time.value)form.end_time.value=`${pad((hour+1)%24)}:${pad(minute)}`;dialog._timePickers?.forEach(fn=>fn())};
      const bump=(part,delta)=>{parse();if(part==='hour')hour=(hour+delta+24)%24;else{const i=minutes.indexOf(minute);minute=minutes[(i+delta+minutes.length)%minutes.length]}commit()};
      trigger.onclick=event=>{event.preventDefault();if(input.disabled)return;closeAll(popover);paint();popover.hidden=!popover.hidden};
      popover.addEventListener('click',event=>{const number=event.target.closest('[data-value]');if(number){parse();if(number.dataset.part==='hour')hour=+number.dataset.value;else minute=+number.dataset.value;commit();return}if(event.target.closest('[data-clear]')){input.value='';paint();popover.hidden=true;return}if(event.target.closest('[data-now]')){const now=new Date();hour=now.getHours();minute=clampMinute(now.getMinutes());commit();return}});
      popover.addEventListener('wheel',event=>{event.preventDefault();const col=event.target.closest('.counter-time-column');bump(col?.dataset.part||'minute',event.deltaY>0?1:-1)},{passive:false});
      trigger.addEventListener('keydown',event=>{if(['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();bump(event.shiftKey?'hour':'minute',event.key==='ArrowDown'?1:-1)}});
      input.addEventListener('change',paint);
      dialog._timePickers=dialog._timePickers||[];dialog._timePickers.push(paint);paint();
    };
    [form.start_time,form.end_time].filter(Boolean).forEach(setup);
    document.addEventListener('click',event=>{if(!dialog.open||event.target.closest('.counter-time-field'))return;closeAll()},true);
  }
  window.openScheduleFeature=id=>open(id?state.schedules.find(x=>x.id===id):undefined);
  function renderCalendarHabits(){
    const list=document.getElementById('habitAnimatedList'),selectAll=document.getElementById('habitSelectAll'),count=document.getElementById('habitSelectionCount');if(!list)return;
    const habits=Array.isArray(state.habits)?state.habits:[],date=todayKey(),parse=key=>{const [y,m,d]=key.split('-').map(Number);return new Date(y,m-1,d)},shift=(key,days)=>{const value=parse(key);value.setDate(value.getDate()+days);const pad=n=>String(n).padStart(2,'0');return `${value.getFullYear()}-${pad(value.getMonth()+1)}-${pad(value.getDate())}`},streak=habit=>{const dates=new Set(habit.dates||[]);let cursor=date;if(!dates.has(cursor))cursor=shift(cursor,-1);let total=0;while(dates.has(cursor)){total++;cursor=shift(cursor,-1)}return total},done=habits.filter(h=>(h.dates||[]).includes(date)).length;
    list.innerHTML=habits.length?habits.map((habit,index)=>{const completed=(habit.dates||[]).includes(date),days=streak(habit);return `<label class="habit-animated-item" role="listitem" data-state="${completed?'selected':''}" style="--habit-index:${index}" tabindex="0"><input data-habit="${habit.id}" type="checkbox" aria-label="Complete ${escape(habit.name)}" ${completed?'checked':''}><span class="habit-animated-copy"><strong>${escape(habit.name)}</strong><small>${escape(habit.description||'Daily habit')}</small></span><span class="habit-animated-streak">${days} ${days===1?'day':'days'}</span></label>`}).join(''):'<div class="habit-animated-empty"><span class="material-symbols-outlined">playlist_add</span><strong>No habits yet</strong><small>Add a habit from the Habits page.</small></div>';
    if(count)count.textContent=`${done} of ${habits.length} habit(s) completed.`;
    if(selectAll){selectAll.disabled=!habits.length;selectAll.checked=!!habits.length&&done===habits.length;selectAll.indeterminate=done>0&&done<habits.length;selectAll.onchange=()=>{habits.forEach(habit=>{habit.dates=Array.isArray(habit.dates)?habit.dates:[];habit.dates=selectAll.checked?[...new Set([...habit.dates,date])]:habit.dates.filter(value=>value!==date)});save();renderCalendarHabits()}}
    list.querySelectorAll('[data-habit]').forEach(input=>input.onchange=()=>{const habit=state.habits.find(item=>item.id===input.dataset.habit);if(!habit)return;habit.dates=Array.isArray(habit.dates)?habit.dates:[];habit.dates=input.checked?[...new Set([...habit.dates,date])]:habit.dates.filter(value=>value!==date);save();renderCalendarHabits()});
    const items=[...list.querySelectorAll('.habit-animated-item')];if('IntersectionObserver'in window&&items.length){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('is-visible',entry.isIntersecting)),{root:list,threshold:.55});items.forEach(item=>observer.observe(item))}else items.forEach(item=>item.classList.add('is-visible'));
  }
  function scheduleTablePage(){
    const tbody=document.getElementById('scheduleRows'),search=document.getElementById('search'),count=document.getElementById('resultCount'),selectAll=document.querySelector('thead .check'),filterButton=document.getElementById('scheduleFilterButton'),tabs=[...document.querySelectorAll('.tab')],cards=[...document.querySelectorAll('.cards .card')];if(!tbody)return;
    const heading=document.querySelector('.headline h1');if(heading)heading.textContent='Schedule Overview';const sub=document.querySelector('.headline p');if(sub)sub.textContent='Manage schedules synced with the main calendar.';
    const cardConfig=[['In Progress','Current activity','Schedules currently in progress','progress'],['Completed','Completion status','Schedules marked as completed','done'],['To Do','Pending schedules','Schedules waiting to be completed','todo'],['Overdue','Needs attention','Unfinished items past their due time','overdue']];
    cards.forEach((card,index)=>{const cfg=cardConfig[index];if(!cfg)return;card.dataset.filter=cfg[3];card.style.cursor='pointer';card.classList.add('schedule-overview-bento');card.querySelector('.label').textContent=cfg[0];const footer=card.querySelector('.card-footer');if(footer)footer.innerHTML=`${cfg[1]}<span>${cfg[2]}</span>`;card.addEventListener('pointermove',event=>{const rect=card.getBoundingClientRect();card.style.setProperty('--bento-x',`${event.clientX-rect.left}px`);card.style.setProperty('--bento-y',`${event.clientY-rect.top}px`);card.style.setProperty('--bento-opacity','1')});card.addEventListener('pointerleave',()=>card.style.setProperty('--bento-opacity','0'));card.addEventListener('pointerdown',event=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const rect=card.getBoundingClientRect(),ripple=document.createElement('i');ripple.className='schedule-overview-ripple';ripple.style.left=`${event.clientX-rect.left}px`;ripple.style.top=`${event.clientY-rect.top}px`;card.append(ripple);ripple.addEventListener('animationend',()=>ripple.remove(),{once:true})})});
    const headerCells=[...document.querySelectorAll('thead th')],headerText=['','Schedule','Status','Date','Type',''];headerCells.forEach((cell,index)=>{if(headerText[index]!==undefined&&cell.lastChild)cell.lastChild.textContent=headerText[index]});if(search)search.placeholder='Search schedules…';
    let filter='all',typeFilter='all';
    const typeOptions=[['all','All Types'],['task','Task'],['deadline','Deadline'],['event','Event'],['match','Match'],['holiday','Holiday'],['other','Other']];
    let typeMenu;
    if(filterButton){typeMenu=document.createElement('div');typeMenu.className='schedule-filter-menu';typeMenu.hidden=true;typeMenu.setAttribute('role','menu');typeMenu.innerHTML=typeOptions.map(([value,label])=>`<button type="button" role="menuitemradio" aria-checked="${value==='all'}" data-type-filter="${value}"><span>${label}</span><span class="material-symbols-outlined">check</span></button>`).join('');filterButton.after(typeMenu);filterButton.onclick=event=>{event.stopPropagation();typeMenu.hidden=!typeMenu.hidden;filterButton.setAttribute('aria-expanded',String(!typeMenu.hidden))};typeMenu.onclick=event=>{const option=event.target.closest('[data-type-filter]');if(!option)return;typeFilter=option.dataset.typeFilter;typeMenu.querySelectorAll('[data-type-filter]').forEach(button=>button.setAttribute('aria-checked',String(button===option)));filterButton.querySelector('[data-filter-label]').textContent=typeOptions.find(([value])=>value===typeFilter)?.[1]||'All Types';filterButton.classList.toggle('active',typeFilter!=='all');typeMenu.hidden=true;filterButton.setAttribute('aria-expanded','false');render()};document.addEventListener('click',event=>{if(typeMenu.hidden||event.target.closest('.actions'))return;typeMenu.hidden=true;filterButton.setAttribute('aria-expanded','false')})}
    const setFilter=next=>{filter=next;tabs.forEach(x=>x.classList.toggle('active',x.dataset.filter===next));cards.forEach(x=>x.classList.toggle('active',x.dataset.filter===next));render()};
    const mapStatus=s=>s==='doing'?'progress':s;
    const render=()=>{const q=(search?.value||'').toLowerCase();const rows=state.schedules.filter(x=>(filter==='all'||mapStatus(status(x))===filter)&&(typeFilter==='all'||x.type===typeFilter)&&(`${x.title} ${x.notes||''} ${labels[x.type]||''}`).toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date)||(b.start_time||'00').localeCompare(a.start_time||'00'));
      tbody.innerHTML=rows.length?rows.map(x=>`<tr data-status="${mapStatus(status(x))}"><td><input data-check="${x.id}" class="check" type="checkbox" ${x.status==='done'?'checked':''}></td><td class="task">${escape(x.title)}<small>${escape(x.notes||'Synced from the main calendar')}</small></td><td><span class="badge ${status(x)==='done'?'done':status(x)==='todo'?'todo':''}"><i class="dot"></i>${labels[status(x)]}</span></td><td>${x.date}${x.end_date&&x.end_date!==x.date?' – '+x.end_date:''}${x.all_day?' · All day':x.start_time?' · '+x.start_time:''}</td><td><span class="badge">${labels[x.type]||'Schedule'}</span></td><td><button data-edit="${x.id}" class="more schedule-row-more" style="background:transparent!important;box-shadow:none!important;border:0!important" aria-label="Edit schedule"><span class="material-symbols-outlined">more_horiz</span></button></td></tr>`).join(''):`<tr><td colspan="6" class="task"><small>No schedules yet. Use Create New to add one.</small></td></tr>`;
      if(count)count.textContent=`${rows.length} ${rows.length===1?'schedule':'schedules'}`;
      const total=state.schedules.length,done=state.schedules.filter(x=>status(x)==='done').length,doing=state.schedules.filter(x=>status(x)==='doing').length,overdue=state.schedules.filter(x=>status(x)==='overdue').length,todo=state.schedules.filter(x=>status(x)==='todo').length;
      const cardNums=[...document.querySelectorAll('.cards .card strong')];[doing,done,todo,overdue].forEach((n,i)=>{if(cardNums[i])cardNums[i].textContent=n});
      tabs.forEach(t=>{const c=t.querySelector('.count');if(c)c.textContent={progress:doing,done,todo,overdue}[t.dataset.filter]??total});
      if(selectAll){const completed=rows.filter(x=>x.status==='done').length;selectAll.disabled=!rows.length;selectAll.checked=!!rows.length&&completed===rows.length;selectAll.indeterminate=completed>0&&completed<rows.length;selectAll.setAttribute('aria-label',rows.length?`Mark all ${rows.length} visible schedules as ${selectAll.checked?'not completed':'completed'}`:'No schedules to select')}
      tbody.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>{const item=state.schedules.find(x=>x.id===c.dataset.check);if(item){item.status=c.checked?'done':'todo';item.updated_at=new Date().toISOString();save();renderAll()}});
      tbody.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(state.schedules.find(x=>x.id===b.dataset.edit)));
    };
    tabs.forEach(t=>t.onclick=()=>setFilter(t.dataset.filter));cards.forEach(card=>card.onclick=()=>setFilter(card.dataset.filter||'all'));if(search)search.oninput=render;if(selectAll)selectAll.onchange=()=>{const q=(search?.value||'').toLowerCase(),visible=state.schedules.filter(x=>(filter==='all'||mapStatus(status(x))===filter)&&(typeFilter==='all'||x.type===typeFilter)&&(`${x.title} ${x.notes||''} ${labels[x.type]||''}`).toLowerCase().includes(q)),next=selectAll.checked?'done':'todo',now=new Date().toISOString();visible.forEach(item=>{item.status=next;item.updated_at=now});save();renderAll();toast(next==='done'?`${visible.length} schedules completed`:`${visible.length} schedules reopened`)};const create=document.querySelector('.kairos-create');if(create)create.onclick=()=>open();window.renderSchedules=render;render();
  }
  const lunarFormatter=new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{month:'long',day:'numeric'});
  const lunarDigits=['\u4e00','\u4e8c','\u4e09','\u56db','\u4e94','\u516d','\u4e03','\u516b','\u4e5d'];
  const lunarDayName=day=>day<=10?(day===10?'\u521d\u5341':'\u521d'+lunarDigits[day-1]):day<20?'\u5341'+lunarDigits[day-11]:day===20?'\u4e8c\u5341':day<30?'\u5eff'+lunarDigits[day-21]:'\u4e09\u5341';
  const isNthWeekday=(date,month,weekday,nth)=>date.getMonth()===month&&date.getDay()===weekday&&Math.ceil(date.getDate()/7)===nth;
  const solarFestivals={
    '01-01':'\u5143\u65e6','02-14':'\u60c5\u4eba\u8282','03-05':'\u5b66\u96f7\u950b\u65e5','03-08':'\u5987\u5973\u8282','03-12':'\u690d\u6811\u8282','03-15':'\u6d88\u8d39\u8005\u6743\u76ca\u65e5','03-21':'\u4e16\u754c\u7761\u7720\u65e5','04-01':'\u611a\u4eba\u8282','04-22':'\u4e16\u754c\u5730\u7403\u65e5','05-01':'\u52b3\u52a8\u8282','05-04':'\u9752\u5e74\u8282','05-12':'\u62a4\u58eb\u8282','05-18':'\u56fd\u9645\u535a\u7269\u9986\u65e5','06-01':'\u513f\u7ae5\u8282','07-01':'\u5efa\u515a\u8282','08-01':'\u5efa\u519b\u8282','09-03':'\u6297\u6218\u80dc\u5229\u7eaa\u5ff5\u65e5','09-10':'\u6559\u5e08\u8282','09-18':'\u4e5d\u4e00\u516b\u7eaa\u5ff5\u65e5','10-01':'\u56fd\u5e86\u8282','10-24':'\u7a0b\u5e8f\u5458\u8282','11-11':'\u53cc\u5341\u4e00','12-13':'\u56fd\u5bb6\u516c\u796d\u65e5','12-24':'\u5e73\u5b89\u591c','12-25':'\u5723\u8bde\u8282'
  };
  const lunarFestivals={
    '\u6b63\u6708-1':'\u6625\u8282','\u6b63\u6708-15':'\u5143\u5bb5\u8282','\u4e8c\u6708-2':'\u9f99\u62ac\u5934','\u4e94\u6708-5':'\u7aef\u5348\u8282','\u4e03\u6708-7':'\u4e03\u5915','\u4e03\u6708-15':'\u4e2d\u5143\u8282','\u516b\u6708-15':'\u4e2d\u79cb\u8282','\u4e5d\u6708-9':'\u91cd\u9633\u8282','\u5341\u6708-1':'\u5bd2\u8863\u8282','\u5341\u6708-15':'\u4e0b\u5143\u8282','\u814a\u6708-8':'\u814a\u516b\u8282','\u5341\u4e8c\u6708-8':'\u814a\u516b\u8282','\u814a\u6708-23':'\u5c0f\u5e74','\u5341\u4e8c\u6708-23':'\u5c0f\u5e74'
  };
  function calendarDateMeta(date){
    const parts=lunarFormatter.formatToParts(date),month=parts.find(x=>x.type==='month')?.value||'',day=Number(parts.find(x=>x.type==='day')?.value||0),solar=String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');
    const qingming=Math.floor((date.getFullYear()%100)*.2422+4.81)-Math.floor((date.getFullYear()%100)/4);
    const floating=isNthWeekday(date,4,0,2)?'\u6bcd\u4eb2\u8282':isNthWeekday(date,5,0,3)?'\u7236\u4eb2\u8282':isNthWeekday(date,10,4,4)?'\u611f\u6069\u8282':'';
    const lunarHoliday=!month.startsWith('\u95f0')?lunarFestivals[month+'-'+day]||'':'';
    const holiday=solarFestivals[solar]||(date.getMonth()===3&&date.getDate()===qingming?'\u6e05\u660e\u8282':'')||floating||lunarHoliday;
    return {lunar:day?lunarDayName(day):'',holiday};
  }
  function noteMarkerForDate(key){
    const notes=Array.isArray(state.notes)?state.notes.filter(note=>note?.date===key):[],mood=state.moods&&typeof state.moods==='object'&&!Array.isArray(state.moods)?state.moods[key]:'';
    if(!notes.length&&!mood)return '';
    const label=`${notes.length?`${notes.length} note${notes.length===1?'':'s'}`:''}${notes.length&&mood?' · ':''}${mood?`Mood: ${mood}`:''}`;
    return `<span class="calendar-note-marker" title="${escape(label)}" aria-label="${escape(label)}"><i class="material-symbols-outlined" aria-hidden="true">edit_note</i>${mood?`<b>${escape(mood)}</b>`:''}${notes.length?`<em>${notes.length}</em>`:''}</span>`;
  }
  function applyDayBorderGlow(cell){
    cell.classList.add('calendar-border-glow');
    const light=document.createElement('span');light.className='calendar-edge-light';light.setAttribute('aria-hidden','true');cell.prepend(light);
    cell.addEventListener('pointermove',event=>{
      const rect=cell.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,cx=rect.width/2,cy=rect.height/2,dx=x-cx,dy=y-cy;
      const kx=dx===0?Infinity:cx/Math.abs(dx),ky=dy===0?Infinity:cy/Math.abs(dy),edge=Math.min(Math.max(1/Math.min(kx,ky),0),1);
      let angle=dx===0&&dy===0?0:Math.atan2(dy,dx)*180/Math.PI+90;if(angle<0)angle+=360;
      cell.style.setProperty('--edge-proximity',(edge*100).toFixed(3));cell.style.setProperty('--cursor-angle',`${angle.toFixed(3)}deg`);
    });
    cell.addEventListener('pointerleave',()=>cell.style.setProperty('--edge-proximity','0'));
  }
  function revealCalendarMonth(grid,heading,direction=1){
    if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
    heading.querySelectorAll('.calendar-reveal-word').forEach((word,index)=>{const animation=word.animate([{opacity:.12,filter:'blur(5px)',transform:`translateY(${direction*8}px) rotate(${direction*3}deg)`},{opacity:1,filter:'blur(0)',transform:'translateY(0) rotate(0)'}],{duration:430,delay:index*70,easing:'cubic-bezier(.2,.75,.25,1)',fill:'both'});animation.onfinish=()=>animation.cancel()});
    grid.querySelectorAll('.day-cell').forEach((cell,index)=>{const animation=cell.animate([{opacity:.08,filter:'blur(4px)'},{opacity:1,filter:'blur(0)'}],{duration:360,delay:Math.min(index*9,260),easing:'cubic-bezier(.2,.75,.25,1)',fill:'both'});animation.onfinish=()=>animation.cancel()});
  }
  function bindCalendarDragDrop(grid){
    let draggingId='';
    grid.querySelectorAll('.calendar-schedule-chip').forEach(chip=>{chip.draggable=true;chip.setAttribute('aria-grabbed','false');chip.addEventListener('dragstart',event=>{draggingId=chip.dataset.scheduleId||'';chip.classList.add('is-dragging');chip.setAttribute('aria-grabbed','true');event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',draggingId)});chip.addEventListener('dragend',()=>{chip.classList.remove('is-dragging');chip.setAttribute('aria-grabbed','false');grid.querySelectorAll('.calendar-drop-target').forEach(cell=>cell.classList.remove('calendar-drop-target'));draggingId=''})});
    grid.querySelectorAll('.day-cell').forEach(cell=>{cell.addEventListener('dragover',event=>{const id=event.dataTransfer.getData('text/plain')||draggingId;if(!id)return;event.preventDefault();event.dataTransfer.dropEffect='move';cell.classList.add('calendar-drop-target')});cell.addEventListener('dragleave',event=>{if(!cell.contains(event.relatedTarget))cell.classList.remove('calendar-drop-target')});cell.addEventListener('drop',event=>{const id=event.dataTransfer.getData('text/plain')||draggingId;if(!id)return;event.preventDefault();cell.classList.remove('calendar-drop-target');moveScheduleToDate(id,cell.dataset.date)})});
  }
  function calendarPage(){
    const grid=document.querySelector('.calendar-grid'),heading=document.getElementById('scheduleCalendarHeading');if(!grid||!heading)return;
    const names=['January','February','March','April','May','June','July','August','September','October','November','December'];
    if(!calendarView)calendarView=new Date(new Date().getFullYear(),new Date().getMonth(),1);
    const y=calendarView.getFullYear(),m=calendarView.getMonth(),cells=monthGrid(y,m);heading.innerHTML=`<span class="calendar-reveal-word">${names[m]}</span> <span class="calendar-reveal-word">${y}</span>`;
    grid.querySelectorAll('.day-cell').forEach(x=>x.remove());
    for(const day of cells){const date=fromDateKey(day.key),key=day.key,cell=document.createElement('button'),dateMeta=calendarDateMeta(date);cell.type='button';cell.className=`day-cell bg-surface-container-lowest p-3${!day.inMonth?' inactive':''}${key===selected?' calendar-day-selected':''}${day.weekday===0||day.weekday===6?' calendar-rest-day':''}${dateMeta.holiday?' calendar-festival-day':''}`;cell.dataset.date=key;cell.innerHTML=`<span class="font-label-sm"><strong>${day.day}</strong><em>${dateMeta.lunar}</em></span>${dateMeta.holiday?`<span class="calendar-holiday" title="${dateMeta.holiday}">${dateMeta.holiday}</span>`:''}${noteMarkerForDate(key)}`;const dayItems=state.schedules.filter(x=>covers(x,key)).sort((a,b)=>(status(a)==='done')-(status(b)==='done')||(a.start_time||'99').localeCompare(b.start_time||'99')),visibleCount=dayItems.length>2?1:2;cell.dataset.visibleSchedules=visibleCount;dayItems.slice(0,visibleCount).forEach(x=>cell.insertAdjacentHTML('beforeend',`<div data-schedule-id="${x.id}" class="calendar-schedule-chip schedule-status-${status(x)}" title="${escape(x.title)}"><i></i><span class="calendar-schedule-title">${escape(x.title)}</span></div>`));if(dayItems.length>2){const hidden=dayItems.slice(visibleCount),colors=[...new Set(hidden.map(x=>status(x)==='done'?'done':'todo'))];cell.insertAdjacentHTML('beforeend',`<div class="calendar-more-chip"><span>+${hidden.length} more</span><b>${colors.map(color=>`<i class="calendar-more-dot ${color}"></i>`).join('')}</b></div>`)}applyDayBorderGlow(cell);cell.onclick=()=>{selected=key;if(!day.inMonth){calendarView=new Date(day.year,day.monthIndex,1);calendarPage();return}grid.querySelectorAll('.day-cell').forEach(x=>x.classList.remove('calendar-day-selected'));cell.classList.add('calendar-day-selected');renderToday()};grid.append(cell)}
    grid.querySelectorAll('.day-cell').forEach(cell=>{
      const dayItems=state.schedules.filter(x=>covers(x,cell.dataset.date)).sort((a,b)=>(status(a)==='done')-(status(b)==='done')||(a.start_time||'99').localeCompare(b.start_time||'99'));
      if(dayItems.length<=2)return;
      const agenda=document.createElement('div');agenda.className='calendar-day-agenda has-overflow';
      [...cell.querySelectorAll('.calendar-schedule-chip,.calendar-more-chip')].forEach(node=>agenda.append(node));
      const more=agenda.querySelector('.calendar-more-chip');
      dayItems.slice(Number(cell.dataset.visibleSchedules)||1).forEach(x=>more.insertAdjacentHTML('beforebegin',`<div data-schedule-id="${x.id}" class="calendar-schedule-chip calendar-schedule-overflow schedule-status-${status(x)}" title="${escape(x.title)}"><i></i><span class="calendar-schedule-title">${escape(x.title)}</span></div>`));
      cell.append(agenda);
    });
    bindCalendarDragDrop(grid);
    revealCalendarMonth(grid,heading,monthMotionDirection);
    const calendarPanel=grid.closest('section');if(calendarPanel&&!calendarPanel.dataset.monthWheelBound){calendarPanel.dataset.monthWheelBound='true';calendarPanel.addEventListener('wheel',event=>{if(event.ctrlKey||event.metaKey)return;event.preventDefault();if(monthWheelLocked)return;monthWheelAccumulator+=event.deltaY;clearTimeout(monthWheelReset);monthWheelReset=setTimeout(()=>monthWheelAccumulator=0,180);if(Math.abs(monthWheelAccumulator)<55)return;monthMotionDirection=monthWheelAccumulator>0?1:-1;monthWheelAccumulator=0;monthWheelLocked=true;setTimeout(()=>monthWheelLocked=false,420);calendarView=new Date(calendarView.getFullYear(),calendarView.getMonth()+monthMotionDirection,1);selected=`${calendarView.getFullYear()}-${String(calendarView.getMonth()+1).padStart(2,'0')}-01`;calendarPage()},{passive:false})}
    document.getElementById('schedulePrevMonth').onclick=()=>{monthMotionDirection=-1;calendarView=new Date(y,m-1,1);selected=`${calendarView.getFullYear()}-${String(calendarView.getMonth()+1).padStart(2,'0')}-01`;calendarPage()};
    document.getElementById('scheduleNextMonth').onclick=()=>{monthMotionDirection=1;calendarView=new Date(y,m+1,1);selected=`${calendarView.getFullYear()}-${String(calendarView.getMonth()+1).padStart(2,'0')}-01`;calendarPage()};
    document.getElementById('scheduleTodayButton').onclick=()=>{const d=new Date();calendarView=new Date(d.getFullYear(),d.getMonth(),1);selected=todayKey();calendarPage()};
    const add=document.getElementById('scheduleAddSlot');add.innerHTML='<span class="material-symbols-outlined text-sm">add</span> Add slot';add.onclick=()=>open();
    const create=document.querySelector('.kairos-create');if(create)create.onclick=()=>open();renderToday();renderCalendarHabits();
  }
  function initScheduleScrollStack(scroller){
    scroller.classList.add('schedule-scroll-stack');
    const cards=[...scroller.querySelectorAll('.schedule-stack-card')];if(!cards.length)return;
    initScheduleMagicBento(cards);
    const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;let frame=0;
    const update=()=>{frame=0;if(reduceMotion)return;const scrollTop=scroller.scrollTop,stackPosition=12,stackDistance=13,end=Math.max(0,scroller.scrollHeight-scroller.clientHeight);
      cards.forEach((card,index)=>{const cardTop=card.offsetTop,trigger=cardTop-stackPosition-stackDistance*index,pinEnd=Math.max(trigger,end-34),active=scrollTop>=trigger,translate=active?Math.min(scrollTop-trigger,pinEnd-trigger):0,progress=Math.min(1,Math.max(0,(scrollTop-trigger)/Math.max(1,card.offsetHeight))),scale=1-progress*(.055-Math.min(index*.008,.035));card.style.transform=`translate3d(0,${translate}px,0) scale(${scale})`;card.style.filter=active&&index<cards.length-1?`blur(${Math.min(1.2,progress*.8)}px)`:'';card.style.zIndex=String(index+1)});
    };
    scroller.onscroll=()=>{if(!frame)frame=requestAnimationFrame(update)};requestAnimationFrame(update);
  }
  function initScheduleMagicBento(cards){
    const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
    cards.forEach(card=>{const surface=card.querySelector('.schedule-stack-surface');if(!surface)return;surface.classList.add('schedule-magic-bento');
      surface.addEventListener('pointermove',event=>{const rect=surface.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;surface.style.setProperty('--glow-x',`${x}px`);surface.style.setProperty('--glow-y',`${y}px`);surface.style.setProperty('--glow-intensity','1')});
      surface.addEventListener('pointerleave',()=>surface.style.setProperty('--glow-intensity','0'));
      if(!reduceMotion)surface.addEventListener('click',event=>{const rect=surface.getBoundingClientRect(),size=Math.max(rect.width,rect.height)*1.8,ripple=document.createElement('span');ripple.className='schedule-magic-ripple';ripple.style.cssText=`width:${size}px;height:${size}px;left:${event.clientX-rect.left-size/2}px;top:${event.clientY-rect.top-size/2}px`;surface.append(ripple);ripple.addEventListener('animationend',()=>ripple.remove())});
    });
  }
  function initScheduleAnimatedList(box){box.classList.remove('schedule-scroll-stack');box.classList.add('schedule-animated-list');box.onscroll=null;box.querySelectorAll('.schedule-animated-item').forEach((item,index)=>item.style.setProperty('--schedule-index',index))}
  function renderToday(){let h=document.getElementById('scheduleTodayHeading');if(!h){h=[...document.querySelectorAll('h4')].find(x=>x.textContent.includes("Today's Schedule"));if(h)h.id='scheduleTodayHeading'}if(!h)return;h.textContent=`${selected} Schedule`;let box=document.getElementById('scheduleTodayList');if(!box){box=h.parentElement.querySelector('.overflow-y-auto');if(box)box.id='scheduleTodayList'}if(!box)return;const items=state.schedules.filter(x=>covers(x,selected)).sort((a,b)=>sortTimeForDate(a,selected).localeCompare(sortTimeForDate(b,selected)));box.innerHTML=items.length?items.map(x=>`<div data-id="${x.id}" class="schedule-animated-item ${status(x)==='done'?'is-done':''}"><span class="schedule-animated-time">${timeForDate(x,selected)}</span><div class="schedule-animated-card"><input data-check="${x.id}" class="task-complete-check schedule-agenda-check" type="checkbox" ${status(x)==='done'?'checked':''} aria-label="Mark schedule complete"><button data-open="${x.id}" class="schedule-animated-content" type="button"><strong>${escape(x.title)}</strong><small>${labels[status(x)]} · ${labels[x.type]}</small></button></div></div>`).join(''):'<div class="schedule-empty">No schedules for this day.</div>';box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(state.schedules.find(x=>x.id===b.dataset.open)));box.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>{const item=state.schedules.find(x=>x.id===c.dataset.check);if(item){item.status=c.checked?'done':'todo';item.updated_at=new Date().toISOString();saveQuiet();const nextStatus=status(item),row=c.closest('.schedule-animated-item');row?.classList.toggle('is-done',nextStatus==='done');const meta=row?.querySelector('small');if(meta)meta.textContent=`${labels[nextStatus]} · ${labels[item.type]}`;document.querySelectorAll(`[data-schedule-id="${CSS.escape(item.id)}"]`).forEach(chip=>{chip.classList.remove('schedule-status-done','schedule-status-todo','schedule-status-doing','schedule-status-overdue');chip.classList.add(`schedule-status-${nextStatus}`)})}});initScheduleAnimatedList(box)}
  function renderAll(){state=load();window.renderSchedules?.();if(document.body.dataset.page==='calendar')calendarPage()}
  window.addEventListener('storage',event=>{if(event.key!==KEY)return;const prevSchedules=JSON.stringify(state.schedules);state=load();window.renderSchedules?.();if(document.body.dataset.page==='calendar'){if(JSON.stringify(state.schedules)!==prevSchedules)calendarPage();renderCalendarHabits()}});
  window.addEventListener('kairos:state-changed',event=>{if(!event.detail)return;const prevSchedules=JSON.stringify(state.schedules);state=normalizeSchedules(event.detail);localStorage.setItem(KEY,JSON.stringify(state));window.renderSchedules?.();if(document.body.dataset.page==='calendar'){if(JSON.stringify(state.schedules)!==prevSchedules)calendarPage();renderCalendarHabits()}});
  window.addEventListener('message',event=>{const message=event.data;if(!message)return;if(message.type==='kairos:open-schedule'){if(window.top!==window&&event.source===window.top&&typeof message.id==='string')open(state.schedules.find(item=>item.id===message.id));return}if(!['kairos:state-sync','kairos:state-request'].includes(message.type))return;if(message.type==='kairos:state-request'){postState(event.source);return}const prevSchedules=JSON.stringify(state.schedules);state=normalizeSchedules(message.state);localStorage.setItem(KEY,JSON.stringify(state));window.renderSchedules?.();if(document.body.dataset.page==='calendar'){if(JSON.stringify(state.schedules)!==prevSchedules)calendarPage();renderCalendarHabits()}if(window.top===window)document.querySelectorAll('iframe.kairos-spa-view').forEach(frame=>{if(frame.contentWindow!==event.source)postState(frame.contentWindow)})});
  document.addEventListener('click',event=>{const close=event.target.closest('#scheduleFeatureDialog [data-close]');if(!close)return;event.preventDefault();event.stopImmediatePropagation();editing=null;document.getElementById('scheduleFeatureDialog')?.close()},true);
  document.addEventListener('change',event=>{const check=event.target.closest?.('.task-complete-check[data-check]');if(!check?.checked)return;const title=check.closest('.schedule-animated-item')?.querySelector('.schedule-animated-content strong')?.textContent||'';reactPet('happy',{title})});
  ensureDialog();document.body.dataset.page==='schedule'?scheduleTablePage():document.body.dataset.page==='calendar'&&calendarPage();if(window.top!==window)try{window.top.postMessage({type:'kairos:state-request'},'*')}catch{}else{broadcastState();window.addEventListener('load',broadcastState,{once:true});[100,400,1000].forEach(delay=>setTimeout(broadcastState,delay))}
  if(window.kairosDesktop){window.kairosDesktop.appState.get().then(next=>{state=normalizeSchedules(next);localStorage.setItem(KEY,JSON.stringify(state));renderAll()});window.kairosDesktop.appState.onChanged(next=>{state=normalizeSchedules(next);localStorage.setItem(KEY,JSON.stringify(state));window.renderSchedules?.();if(document.body.dataset.page==='calendar'){if(Date.now()<quietSaveUntil){renderCalendarHabits();return}calendarPage();renderCalendarHabits();}})}
})();
